### ISSUE TITLE
IDE can not load a project on startup

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1000]
**Describe the bug**
every ide is able to start at least one file via command line interface. Even NOTEPAD can do that :)
To reproduce start twinbasic with a project filename.
nothing happens.

It would be nice if the IDE can separte between a folder and a project and import things from it (exe or dll  project)

and it would be more nice if the IDE could get a second switch which tells to compile / build directly :)

so a possible call would be
twinbasic filespec   /dll | exe | whatever   /compile

**Comment by bclothier** [comment]
FWIW, a quick registry script to help out. This lays out the groundwork for supporting opening & creating new files and giving them a pretty icon. Note that open technically does not work because as indicated, there must be a command line switch to pass in the file name so right now it will simply open the IDE but not open the specific project. 

Of course, the paths in the script need to be adjusted to wherever the IDE is. To avoid requiring admin privileges, this can be used in HKCU\Classes instead of HKCR. 

![image](https://user-images.githubusercontent.com/2367644/180087636-b47961dc-e15c-4cd0-8641-3be98fccd936.png)

It may be worthwhile creating a new icon that has a file with tB logo on it to help differentiate it from the executables that has the full tB logo.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.twinproj]
@="twinBasic.Project"

[HKEY_CLASSES_ROOT\.twinproj\twinBasic.Project]

[HKEY_CLASSES_ROOT\.twinproj\twinBasic.Project\ShellNew]
"FileName"="C:\\TwinBasic\\IDE\\BlankProject.twinproj"

[HKEY_CLASSES_ROOT\twinBasic.Project]
@="twinBASIC Project"

[HKEY_CLASSES_ROOT\twinBasic.Project\DefaultIcon]
@="F:\\TwinBasic\\IDE\\twinBASIC.exe"

[HKEY_CLASSES_ROOT\twinBasic.Project\shell]

[HKEY_CLASSES_ROOT\twinBasic.Project\shell\open]

[HKEY_CLASSES_ROOT\twinBasic.Project\shell\open\command]
@="\"C:\\TwinBasic\\IDE\\twinBASIC.exe\" \"%1\""
```

**Comment by WaynePhillipsEA** [comment]
With regards to the registry script, given the lack of a tB IDE installer, I guess we could have the twinBASIC IDE reconfigure the paths each time it is launched, so that the last opened version of tB is registered for the shell extensions.

**Comment by WaynePhillipsEA** [comment]
BETA 80 adds the ability to launch the IDE passing a filepath to a twinproj file.  The other parts of the request are covered by #508 .  Thanks.
