### ISSUE TITLE
Beware bloatage

### ISSUE THREAD

**Issue by mansellan** [twinbasic/twinbasic#101]
Is your feature request related to a problem?
twinBASIC should remain as lean as possible.

Additional context
Modern languages provide rich libraries to ease the developer experience. For example, the C# `System` namespace is huge and all-encompassing, catering for everything from string manipulation to Active Directory member enumeration. Whilst this is convenient for the developer, it also leads to runtimes in the hundreds of megabytes. This is to be avoided, and was a big reason behind the "Net Core" reset.

twinBASIC should be cautious of any feature request that doesn't **absolutely require** language support. If I want generic Collections support, I should be free to select a library to achieve that. If not, I shouldn't need to pay the cost of including it.

**Comment by WaynePhillipsEA** [comment]
Whilst I share your concern, the tB linker already picks and chooses what it needs to include in the compiled file.  So for example, if you only call MsgBox from the VBA.Interaction module, it won't pull in anything else like InputBox.  This is what keeps the compiled size of tB executables really low.

My concern with bloatage is more along the lines of cluttering the global namespace.  That's why I really like #100

**Comment by bclothier** [comment]
To clarify, the bloatage isn't about the resulting file size but rather the language features. It happened that mansellan and I were talking about the evolution of various programming languages, we agreed that one thing that C# did well was to have most of the power provided by the Base Class Library (e.g. the framework itself) rather than within the language itself. 

Thus the concern is that if we have a feature request that can be solved by providing a library as opposed to providing a language feature, we should prefer former over the latter as a general rule. A library can be replaced and updated more easily. Once a language feature is introduced, they are more or less written in the stone, frozen for perpetuity. After all, that's why we're still stuck supporting `DefType` even though <1% of people use them.

To use #100 as an example, I really do like Mat's suggestions of providing `Extends`, which is a language feature but it would at least enable people to contribute their domain-specific solutions by writing their own extension methods. tB can then provide the base functionality from its BCL with `Extends` being the only language feature. 

Hope that makes sense?

**Comment by WaynePhillipsEA** [comment]
Yes, I agree with all of that.  For similar reasons you see the upcoming vbWatchdog and web server in the project references list, as I believe most things going forward should be optional includes, rather than being forced into every project.  Compile times can also be affected if we add too much bloat to the language, so I'm acutely aware of it.

I'm going to pin this issue, as I suspect it will be referenced a lot.

**Comment by graysuit** [comment]
1. What I like about b4a (basic4android - an android app developer) that it tells me that `xxx lib is unnecessary`, `xxx variable is unused`.
So by this way, I don't add useless chunks to code.

2. And code needs to be more cleaner than binary.
Because all maintenance depend on code.

3. And what I like about nuget package manager is that,
its like you hired folks to contribute to your framework. 
Suppose I know nothing about excel file format, I will simply search some excel lib in nuget package manager and use it. (and at end call myself as programmer. lol) 

4. And at final, assume yourself inside 1990 pc where there low disk space, almost no internet, very low ram and low resources. Then after, it would become a real vb6 successor.

**Comment by bclothier** [comment]
I am going to close this issue because ultimately, this isn't very actionable. If there's a bloat in a specific area, open an issue focusing on that so that it can be acted upon.
