### ISSUE TITLE
AddressOf errors when used to refer to own procedure in function call under certain circumstances

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1049]
**Describe the bug**
TB removes some limits on AddressOf, but an error still occurs if used in a function call within the function it's pointed at. This appears to only happen when there are ByVal arguments.

**To Reproduce**
The following code in a Module (not tested elsewhere):

```
   Public Function Test1(ByVal hWnd As LongPtr, adr As LongPtr) As LongPtr
        Call Test2(AddressOf Test1)
    End Function
    
    Public Function Test2(ByVal hwnd As LongPtr) As LongPtr
        Call Test1(hwnd, AddressOf Test2)
    End Function
    
    Public Function Test3(hwnd As LongPtr) As Long
        Call Test1(hwnd, AddressOf Test3)
    End Function
```

Only Test3 does not display error "expected procedure for AddressOf".

**Expected behavior**
AddressOf should work in these circumstances.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.86

**Additional context**

**Comment by wqweto** [comment]
Does the usual fix (that works in VB6) fix it in TB i.e. using fully qualified routine name `AddressOf Module1.Test2`?

**Comment by fafalone** [comment]
Seems to yes. But I thought it was meant to avoid that limitation, given that for some reason it's not necessary so long as there aren't ByVal arguments in that function... which seem completely irrelevant. 

Didn't know that trick in VB6 actually btw, hence the separate function, thanks.

**Comment by wqweto** [comment]
Btw, in VB6 you don't need a separate `FARPROC` function too but can use built-in conversion function instead like `VBA.CLng(AddressOf Module1.Test2)` directly.

Note that bare `CLng` is an intrinsic so it has little to do with `VBA.CLng` and is handled by the compiler with direct calls to (multiple) exports from runtime (i.e. `msvbvm60.dll`). The intrinsic cannot be used with `AddressOf` operator the way `VBA.CLng` can.

Btw, you can use the VB IDE to figure out which routine is implemented as an intrinsic and which really calls into `VBA` export by noticing syntax error raised. For instance
```
    Debug.Print VBA.CLng(AddressOf StrComp)
    Debug.Print VBA.CLng(AddressOf StrConv)
    Debug.Print VBA.CLng(AddressOf VBA.StrComp)
```
The first line is a syntax error because `StrComp` is an intrinsic while in the second line `StrConv` is not a syntax error so it's actually really compiled to a call to `VBA.StrConv` and finally the 3-rd line is obviously explicitly not an intrinsic.

**Comment by bclothier** [comment]
FWIW, in VBIDE, you can make them stand out.
![image](https://user-images.githubusercontent.com/2367644/181523416-daf2dfbd-9f3e-41d8-80b6-ad0d86970421.png)

By default, the VBIDE uses same coloring for keyword / normal keywords. Using different colors help make that distinction.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 102, thanks.
