### ISSUE TITLE
[LINKER] compilation (codegen) error

### ISSUE THREAD

**Issue by KimVes** [twinbasic/twinbasic#1076]
**Describe the bug**
[LINKER] compilation (codegen) error detected when I Make/Build...

**To Reproduce**
I have imported a major vbp project. Fixed all the Problems issue. Everything looks nice (no errors) until I try to build a dll-file of the project. The project is a ActiveX-dll.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/97192123/182327439-371a65a2-7ec1-49ef-a9d5-d55aaff87b1e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE_BETA_89

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Thanks for opening the issue.  Are you able to share the project file? (either publicly here, or privately on discord or email)

**Comment by KimVes** [comment]
Yes, I can send you the project file on email. What email to use?

This is a very large project. If I remove 200 class files, then the project will build. So, maybe there is some memory issue?

**Comment by WaynePhillipsEA** [comment]
It doesn't look like a memory issue.  It looks like a codegen issue involving the IsMega2 global variable.   You can reach me at my first name `@twinbasic.com`  Thanks.

**Comment by WaynePhillipsEA** [comment]
Thanks for sending over the file.  I had a quick look, and yes there are some codegen errors, but also you are quite right that there is a memory issue in compiling this project.  I temporarily added the LARGEADDRESSAWARE flag to the compiler to test it further, but the memory use still climbs too much to compile it on 32-bit at the moment (passes 3.5Gb and crashes due to lack of RAM).

So I'll tackle this in stages.   At first, I will just work on fixing the codegen errors as they are most important.

**Comment by KimVes** [comment]
OK, good that you see the issue. Thank you.

**Comment by WaynePhillipsEA** [comment]
How large, in MB, is the VB6 generated build from this project?

**Comment by KimVes** [comment]
In P-Code the dll is 19MB, and with Native Code 45 MB

Luckily it still compiles in VB6

**Comment by WaynePhillipsEA** [comment]
I've managed to get it to compile in tB.   The codegen errors disappeared once the LARGEADDRESSAWARE flag is used, so the codegen errors were also linked to the RAM issue.   So the only problem here is the excessive RAM use during compilation.

FYI, the tB generated build is 185MB, but bear in mind that the code being generated by tB is currently unoptimized, which causes a much larger build size.   Once LLVM compilation is available, this will reduce substantially.

**Comment by KimVes** [comment]
I activated LARGEADDRESSAWARE, but I still get the same problem. I have 28GB RAM in my pc

**Comment by WaynePhillipsEA** [comment]
> I activated LARGEADDRESSAWARE, but I still get the same problem. I have 28GB RAM in my pc

You won't be able to get this working at your end yet, please wait for next release.

**Comment by KimVes** [comment]
OK, no problem, Thank you!

**Comment by WaynePhillipsEA** [comment]
Your project should now build with BETA 91.  Please turn on the LargeAddressAware setting for the IDE (Tools menu > IDE Options...).  After turning that setting on, restart the IDE, and the project should build.  With the improvements made to codegen in BETA 91, your project now builds to about 125MB (rather than the 185MB previously mentioned).

I'll close this, as I believe it is now fixed.  Let me know if you encounter any further problems.
