### ISSUE TITLE
Find In Files makes hang on closing tB

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1155]
**Describe the bug**
When a Find In Files tab is open, it's not possible to close tB.

**To Reproduce**
1. Find In Files in a project.
2. Close tB.

**Expected behavior**
tB shutting down normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/189516980-814e540d-8e65-479c-aec1-192ff3cd28ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 GERMAN
 - twinBASIC 118

**Additional context**
A floating dialog would be better imo, MZ-Tools has a nice solution for VB6.
A doubleclick onto a result in the tree selects in the source and, very good, sets the focus to the code window.
![image](https://user-images.githubusercontent.com/88059532/189517270-31fa78a5-bdb2-4ff3-ab00-12b613fd8356.png)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 121, thanks for reporting!   

The Find/Replace functionality will most certainly be redone at some point.  The current 'Find In Files' implementation is based on the old VS Code implementation where you can't have modal dialogs, and the built-in Find functionality didn't work with virtual filesystems at the time (... though that might've changed by now).
