### ISSUE TITLE
Issue1188

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1230]
Beta141 and 142 with control arrays are an important step again forward! :)
.
If it is possible, I would like to ask you to implement control.zorder, .setfocus and label.backstyle with a little priority.

**Comment by wqweto** [comment]
What's the reason for this? Do these unlock some other blocked feature? What's the rationale for these being implemented ahead of schedule? I'm sure these will get implemented at some point but just cannot understand why the hurry.

Is it possible there's some feeling of entitlement because of being an early paid adopter? This is a very curious interaction (how pre-orders can actually backfire) I've never seen in other projects here on github.

**Comment by WaynePhillipsEA** [comment]
I understand the urge to express your wanted/needed features, though I kindly ask to refrain from doing so here as it is not particularly helpful since everyone has different needs and priorities.

Rest assured, the missing UI features are all high priority.

Thanks for your understanding.

**Comment by DinyaZ** [comment]
Wayne, I hope, that all opinions and all supporter are important. But now
for example if "fafalone, discord" wants something, that it ok, but I get
negative reactions from you when I asks something (IDE, control properties,
etc)
I dont understand why.
Zoltan Dinya

WaynePhillipsEA ***@***.***> ezt írta (időpont: 2022. okt.
7., P, 23:25):

**Comment by WaynePhillipsEA** [comment]
All opinions matter here, and I can assure you that I generally do not pick and choose which issues to tackle based on who reported or asked for them!  More often than not, issues are picked because I'm already doing work in that area of the codebase so it makes sense to tackle related issues.

I do not want lots of separate issues opened on here (GitHub) that say 'I need xyz prioritized please'.  It's not helpful since everyone has different priorities, and it ultimately puts pressure on me.  That's why I created the big #1188 issue so that all the UI missing properties etc are in one place.

Discussions about which things need priority would be more welcome over on discord, or as a comment in the #1188 thread.
