### ISSUE TITLE
OptionButton array behavior differs from VBx

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1234]
**Describe the bug**
In tB, if you make an array of option buttons, but don't define any with Value = True during design time, tB sets index 0's Value to True when you run. In VBx, it just leaves them all false. While tB's behavior may make sense, no doubt there's existing codebases relying on the VBx behavior, and I don't think breaking that is the way to go; we want projects to work without change.

**To Reproduce**
New standard EXE

Create OptionButton array

Run

**Expected behavior**
Same behavior as VB6.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.142

**Additional context**

**Comment by dmrvb** [comment]
As a general observation, there are loads of oddities in the VB6 GUI (or maybe I just don't understand them) and I am not sure that TB will ever get 100% compatability with these. I have sometimes suspected that some change with new versions of Windows, and possibly even with CPU speed. Which control gets the Focus when a Form is loaded/activated is one of the things that causes me some pain. Its better to set these things explicitly in code rather than relying on default VB behaviour.
I realise that 100% compatabiity is the goal but maybe its best not to spend too much time on these things at this stage. I have wasted hours and hours trying to work-around GUI anomolies.

**Comment by fafalone** [comment]
Ok well now it's not doing it in VB6 either... I absolutely double checked before posting this but I can't recall maybe if there was something about how I set it up? Or something went wrong with the VB instance? But then the only reason I checked was because I recalled that behavior from the past... forgetting to set a default during design and having to go back and do it. Well nevermind I guess, either it's a quirk under circumstances or I'm just going crazy (although the voices in my head say I'm totally sane! lol).
