### ISSUE TITLE
Add 'Update package' option in references

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1320]
**Is your feature request related to a problem? Please describe.**
The single-file projects currently import the .twinpack packages and save them as they existed as the time of add. It's a pain to have to entirely remove the reference, freaking the compiler out with hundreds of errors, then adding it back in, when you want to update it to a more recent build of the package.

**Describe the solution you'd like**
Add a button to update the selected package in the references box.

**Describe alternatives you've considered**
Continuing to do it manually.

**Additional context**
Is the feature to upload packages coming back? I would like to add my tbShellLib project at some point; or is this still possible if I installed the old VSCode extension, even though it would think it full of errors?

**Comment by Greedquest** [comment]
Update packages I guess you're taking about a `Replace` button that lets you manually select the twinpack you want to update to and doing the remove + add back in one step to avoid any intermediate broken state?

Because automatically updating with an `Update` button sounds much harder. Where are versions registered, do you always want the latest version, where are filepaths registered etc.?

Or do you envisage a `Refresh` button that looks at the filepath of an old twinpack and sees if there is a newer version at that same location, then updates that? Again what is newer - more recent creation date, semantic version meta-data?

What about, in the references table, we untick the old package, DON'T SAVE CHANGES, browse for the updated version and tick that, then save changes to the settings file. tB should be able to do that atomically with no in-between state.

**Comment by Greedquest** [comment]
Of those 4 options, 2 is the most comprehensive but 4 is the simplest to implement whilst being a workflow I'm surprised doesn't already exist.

**Comment by fafalone** [comment]
I didn't mean for tB to start debating whether or not the version that's at the exact same location as the original is "newer", that's the programmers responsibility. If they don't want it updated from the previous location, the regular remove->add would be more appropriate.

This is how it will work in non-integrated projects when tB supports them anyway I'd assume (more like a .vbp file); it's not going to do any analysis, just load the specified file. 

It does appear you don't need to save, but there's still no reason to not have the simplicity of a button rather than remove and go through a file browser.
