### ISSUE TITLE
The controls in forms lost its visbility after undo an action

### ISSUE THREAD

**Issue by haplox** [twinbasic/twinbasic#1365]
**Describe the bug**
The controls in forms lost its visbility after undo an action

**To Reproduce**
1. Change something in any control in your form
2. Undo the changes
3. See error

**Expected behavior**
TH form to be redrawn after an undo, showing all the controls

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64
 - twinBASIC 177

![GIF 16-11-2022 13-01-39](https://user-images.githubusercontent.com/10757873/202176516-0c17bc4f-888e-4c92-8703-e090604ab482.gif)

**Comment by haplox** [comment]
Anyone more having this problem? Sorry for bumping the post, but it is very unpleasant to have to close/reopen the project to restore the visibility.

Thanks

**Comment by wqweto** [comment]
> Anyone more having this problem? Sorry for bumping the post, but it is very unpleasant to have to close/reopen the project to restore the visibility.
> 
> Thanks

One has to be prepared for the dangers of using software in BETA development phase i.e. everything can be broken at any time :-)) 

Obviously this works for most other users just not in your case but if you can make a minimal reproduction project exhibiting the problem at hand and then upload it here I'm positive the fix will land in some next BETA very fast.

**Comment by WaynePhillipsEA** [comment]
I've tried to reproduce this, but haven't succeeded yet.  As @wqweto mentioned, a minimal project that exhibits the problem would help move this along.

**Comment by haplox** [comment]
Thanks for your answer @WaynePhillipsEA , I suspect that the prblem appears as the project goes on growing, and ther are a lot of controls in it.

As I am not sure of this, I upload my project to see if the cause is another one

Thanks
[avellanados.zip](https://github.com/twinbasic/twinbasic/files/10138819/avellanados.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks, I've managed to reproduce the problem with your file.  

First thing I noted was how much the rendering of the designer grid is affecting the form designer render times.  With you having the grid indicators set to 5x5 pixels, on a big form it's very slow to render.   So any change of form properties, or in fact any change of any property of any lightweight control (like labels) is causing huge delays.  Turning the grid indicators off makes things much more responsive, until this is fixed in the next release.

The above doesn't fix the problem though... but at least I can repro this now.
