### ISSUE TITLE
Imported VB6 Project not loading after saved to twinproj

### ISSUE THREAD

**Issue by OldMcWeb** [twinbasic/twinbasic#1466]
I Imported a VB6 Project, compiled it, everything seems ok.
Then I saved it as a  twinproj Project.
When I try to load it, it takes forever. After 20min. i closed the Application.
In the Debug Console "restarting from File" is printet in an endless loop.
At the bottom of the Screen there are error messages:
COMPILER:Disconnected
FS:Disconnected
LSP:Disconnected
DEBUGGER:Disconnected

* Import a VB6 Project
* Make sure it compiles.
* save it as a twinproj
* close twinBasic
* reopen it and try to load the twinproj file

![grafik](https://user-images.githubusercontent.com/26406067/212870221-7f97a180-bc5a-4e44-9977-40d7dd5f240b.png)

 - OS: Windows 10
 - twinBASIC IDE BETA 233

**Comment by WaynePhillipsEA** [comment]
I can't reproduce a problem here, so it is likely that the problem is occurring more specifically with your project.  Would you be willing to share the twinproj file so that I can take a look?

One possibility, is that when importing a VBP, if you've got references that have relative paths to a type library, this will work when you first open it, but if you save it to a different location, the relative paths are then invalid.  If when you open the project there are missing/unavailable references, this does increase the chance of a crash.

**Comment by WaynePhillipsEA** [comment]
As we haven't heard back, I'll close this.  If you can provide a sample VBP that demonstrates the issue, please attach and then we can reopen.  Thanks.
