### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by sjk7** [twinbasic/twinbasic#1472]
Am I just being dumb? On github, there are not any source files ...?
Thanks!

**Comment by mburns08109** [comment]
Bir yet.
@WaynePhillipsEA has plans to relase the source to the IDE - but not for the compiler itself.

**Comment by sjk7** [comment]
Good, concise answer, thanks, even if a little disappointing. 

I worry with projects like this. If something happens (God forbid) to @WaynePhillipsEA  then where does that leave the users? How can I convince colleagues that it's OK and safe to use a closed source compiler?

We are so used to having compiler source in the C++ community, it might be an uphill struggle to do that ...

**Comment by VB6-Programming** [comment]
> Good, concise answer, thanks, even if a little disappointing.
> 
> I worry with projects like this. If something happens (God forbid) to @WaynePhillipsEA then where does that leave the users? How can I convince colleagues that it's OK and safe to use a closed source compiler?
> 
> We are so used to having compiler source in the C++ community, it might be an uphill struggle to do that ...

Wayne seems open to putting the source code in Escrow.

**Comment by fafalone** [comment]
What Microsoft did with VB6 is precisely why a lot of developers are extremely hesitant to use closed source again. And when even .NET has the open source Roslyn compiler because even MS can't keep it closed... Honestly I don't know how viable escrow even is... I know those of us around now likely trust Wayne, but corporate purchasing and legal departments are going to be a whole different ballgame, and there's been a lot of problems with legal disputes over release events, then you have to worry about trusting the beneficiaries too... who exactly will have legal standing to enforce a release, and is their reputation sufficient that they're trusted to open source it after obtaining it from the escrow company? Going to be a lot of hard questions.

Hopefully tB succeeds to the point a revenue-generating open source model becomes viable for Wayne.

**Comment by kismert1** [comment]
> I worry with projects like this. If something happens (God forbid) to @WaynePhillipsEA then where does that leave the users? How can I convince colleagues that it's OK and safe to use a closed source compiler?

I have to admit, this is disappointing news. I understand why Wayne doing it this way, but still. We all hope this language takes off, and becomes commercially viable. But under the current circumstances, if that happens the tB user community will still have to deal with the uncomfortable feeling that they could get locked-in to a defunct language platform (the same thing that VB6 and Access users face). One day, support could just go away (or get crippled). Eventually, clients can't properly be serviced. The client is then locked in, and sooner or later has to face an expensive migration to some other (hopefully more permanent) platform. That's a story I want to move away from with Access.

This is another way of saying that "No Lock-in" is a powerful phrase to use if you are pitching a tB solution to a client.

> Wayne seems open to putting the source code in Escrow.

This is the minimum commitment. The code should become open source in the event the company fails. This would prevent some other company buying the IP and swallowing it (like Microsoft did with FoxPro) in an attempt to force tB users to adopt some other platform.

On the other hand, I would not be opposed to Wayne offering an extra-cost upgrade that allows a user access to the source. We will all be good users and respect the tB license, won't we?

> We are so used to having compiler source in the C++ community, it might be an uphill struggle to do that ...

I can't tell you how many times I ran into a VB6/VBA issue, and wished I could see how they implemented it in the source. It would have saved many hours of searching, experimenting, and sometimes failing to come up with the 'best' solution.

Wayne wants to make money with tB, and that's totally fine. A thriving company would be the best way to keep tB updated, bug-free, and up to speed with the latest technologies.

But, the tB community needs reassurances that their own consulting businesses (and client's interests) will not be harmed in the (we hope very unlikely) event that Wayne's company fails.

tB is a very interesting language, with a lot of potential. I submit that having a good "no lock-in" story for clients will help realize that potential.

**Comment by WaynePhillipsEA** [comment]
First, I must emphasize that this has been a closed-source, commercial project from the start, and I've always been upfront about that.  That said, things are not set in stone on this project.  Having spent a not-insignificant portion of my life on this project over the last few years, I most certainly would not want to see tB fail at this stage, and I am determined to ensure that does not happen.

Commercially, things are working out OK right now... we're roughly where I would expect to be at this point (given the BETA state).  I would love to see tB open-sourced eventually, but I suspect that it would require some sort of corporate sponsorship, or thinking outside-the-box... perhaps something like a community buy-out.   There's so many possibilities, so certainly don't discard the possibility of tB going open-source at some point in the future.

**Comment by mburns08109** [comment]
> ...I would love to see tB open-sourced eventually...

Preferably after actually being able to AFFORD to get that Lambo...right?  ;-)

**Comment by DinyaZ** [comment]
> This is the minimum commitment. The code should become open source in the event the company fails. This would prevent some other company buying the IP and swallowing it (like Microsoft did with FoxPro) in an attempt to force tB users to adopt some other platform.

.
.
.
Did you remember, what happened with the Jabaco? (https://www.jabaco.org/)
.
This was the best try, before TWB of course, to create a "new VB6". And one day the developer simply disappeared, when the project was in a very promising beta phase. He didnt die, and there was no medical reason, just disappeared. A few times, once a year or so wrote on the forum, that a project lives, but nothing happened. 
I hope that it was not the Microsofts money also.

**Comment by DinyaZ** [comment]
> > This is the minimum commitment. The code should become open source in the event the company fails. This would prevent some other company buying the IP and swallowing it (like Microsoft did with FoxPro) in an attempt to force tB users to adopt some other platform.
> 
> . . . Do you remember, what happened with the Jabaco? (https://www.jabaco.org/) . This was the best try, before TWB of course, to create a "new VB6". And one day the developer simply disappeared, when the project was already in a very promising beta phase. He didnt die, and there was no medical reason, just disappeared. A few times, once a year or so wrote on the forum, that a project lives, even promised a new version, but nothing happened. Later the remnants of community asked him to publish the code if he doesnt want to continue, but he refused this. I hope that it was not Microsofts money also.

**Comment by fafalone** [comment]
Yeah with MS even moving to kill VBA now, it's a fair question what's going to happen if MS shows up at Wayne's door with a 7-8 figure check in one hand and lawsuit service in the other (MS can easily bankrupt people with a meritless suit) and asks which way this will go. If the owner (either original or if the rights are sold) is around to dispute the escrow release events, that means costly litigation and poor chances. Like say the VB6 source was in escrow... MS would very likely succeed in arguing that them updating the runtime to keep it working once every few years means it's not abandoned, so a 'release if abandoned' clause isn't met, and that's if someone hired a lawyer to attempt to enforce an escrow release over objection.

Like I said... lots of hard questions for anyone putting big money on the line choosing a development platform. It's much easier for me as I'm just a hobbyist.

**Comment by DinyaZ** [comment]
> This was the best try, before TWB of course, to create a "new VB6". And one day the developer simply disappeared, when the project was already in a very promising beta phase. He didnt die, and there was no medical reason, just disappeared. A few times, once a year or so wrote on the forum, that a project lives, even promised a new version, but nothing happened. Later the remnants of the community asked him to publish the code if he doesnt want to continue, but he refused this.
> I hope that it was not Microsofts money also.

.
.
.
By the way I think it is not impossible to create and maintain a compatible product. For example MS Office (Word, Excel, etc) is an actual MS product, but Libreoffice (https://www.libreoffice.org/) is full compatible, read and write Office files, and overall it is a very similar product.
.
(The abovementioned Jabaco was a 100% copy of VB6 IDE)

**Comment by DinyaZ** [comment]
> Yeah with MS even moving to kill VBA now, it's a fair question what's going to happen if MS shows up at Wayne's door with a 7-8 figure check in one hand and lawsuit service in the other (MS can easily bankrupt people with a meritless suit) and asks which way this will go. If the owner (either original or if the rights are sold) is around to dispute the escrow release events, that means costly litigation and poor chances. Like say the VB6 source was in escrow... MS would very likely succeed in arguing that them updating the runtime to keep it working once every few years means it's not abandoned, so a 'release if abandoned' clause isn't met, and that's if someone hired a lawyer to attempt to enforce an escrow release over objection.
> 
> Like I said... lots of hard questions for anyone putting big money on the line choosing a development platform. It's much easier for me as I'm just a hobbyist.
.
.
.
By the way I think it is not impossible to create and maintain a compatible product. For example MS Office (Word, Excel, etc) is an actual MS product, but Libreoffice (https://www.libreoffice.org/) is full compatible, read and write Office files, and overall it is a very similar product.
.
(The abovementioned Jabaco was a 100% copy of VB6 IDE)

**Comment by fafalone** [comment]
An office suite is a different thing from a compiler and IDE... notably, LibreOffice *doesn't* have VBA-compatible macros and UserForms, and is lacking some other features that hinder enterprise adoption.

**Comment by kismert1** [comment]
I would love for tB to become a stable, viable language. If this happens, the idea of becoming a consultant who converts old VB6 and VBA code bases into tB becomes attractive. 
If I am making money selling services based on tB, of course I would want to subscribe, and support the company.
But I cannot in good conscience sell these services based on a language whose survival depends on the existence of a small tech startup company.
If the potential client asks about lock-in, as things stand now, I would be forced to say that this is a risk.
I can't build a business based on that.
If @WaynePhillipsEA wants to build a language that works in the professional arena, he will have to address the lock-in issue.

**Comment by mburns08109** [comment]
@kismert1 
Can we get to version 1.0 of tB before we start arguing about the economics and strategy of a product that's not yet quite "real"?

I've been thinking about "the Microsoft deal" a bit (scenario of them coming to @WaynePhillipsEA with a suit in one hand and a check in the other...) and I think @WaynePhillipsEA is in a better position than others may have been because he's chosen to use different, newer technological bases for his efforts. That would bolster his arguments against the lawsuit-hand - and perhaps reduce the allure of that check in the other hand.

**Comment by fafalone** [comment]
There's still time but I'd assume reaching 1.0, coming out of beta, marks the start of serious commercialization efforts, and when a lot of people will be taking their first look at tB. So the next few months is definitely when some of these issues will have to be addressed, since we're (hopefully) only 5 months out from that now.

**Comment by dmrvb** [comment]
If there was any threat  of legal action from Microsoft then tB would likely have to end, Wayne just does not have the resources to fight Microsoft.  But, tB is a modern version of Basic so it is not VB, it just happens to be VB compatible. If there is a real fear of legal issues then tB should to change to emphasise its modern language features and not be VB compatible itself, then some "third party" (the people here with Waynes help) can produce a fully automatic upgrade tool.

**Comment by JBEJBE** [comment]
Always thought, that Wayne asked for legal permission from MS, before going on his year-long mission. If not, no one knows for sure what will happen. Chances of legal actions rise with the rate of success. Chances of open-sourcing TB are thin. Would MS accept publishing their intellectual property for everyone to copy and market for free? Please answer for yourself. 

TB most likely needs to stay closed source, with all inherent downsides. Being a small company is no obstacle. The huge MS company left thousands suddenly stranded on a lonely VB6 beach. Size doesn't matter to me.

But the legal side should be handled with more care. This could destroy all our hopes, if done wrong. Asking MS timely for their legal position regarding a VB6 clone could be a good idea (please consult your trusted lawyer before doing so). Then finding a way to fulfill/circumvent the directives from MS to be on the safe side. Finger crossing might be no convincing solution for this great product.

**Comment by GaryMiller** [comment]
As long as enough improvements are made then it is no longer a clone.  A chief improvement being made is 64 bit!

Keep track of a list of differences and improvements between TwinBasic and VB6 possibly with superior controls with more properties and greater flexibility.  The ability to generate web assembly on the backend could be another key differentiator.

**Comment by GaryMiller** [comment]
As long as enough improvements are made then it is no longer a clone.  A chief improvement being made is 64 bit!

Keep track of a list of differences and improvements between TwinBasic and VB6 possibly with superior controls with more properties and greater flexibility.  The ability to generate web assembly on the backend could be another key differentiator.

**Comment by GaryMiller** [comment]
The bigger fear I think is the Microsoft Men in Black show up on the doorstep with a suitcase of money and it disappears.

**Comment by fafalone** [comment]
Giving permission is against Microsoft's interests... they'd say no even if they didn't think a lawsuit or buyout was worthwhile. 

But yes Wayne should definitely talk to an IP lawyer sometime before V1... but from my admittedly limited knowledge, I don't believe MS would have a winning lawsuit, because Wayne is obviously not reverse engineering the VB6 source and putting it into tB, and simply making a language that's compatible with the syntax of another isn't infringing, nor is making it interoperable when you're not simply copying their code. The danger I see, however, isn't a winning lawsuit, it's that a behemoth like MS can bankrupt small companies and individuals with the costs to defend against an entirely frivolous suit. 

> Would MS accept publishing their intellectual property for everyone to copy and market for free? Please answer for yourself.

Well, they did open source the .NET compiler. Open source isn't synonymous with no IP rights or not charging, and if tB did become successful enough, there are models for sustaining a business based on an open source product... enterprise support contracts can be big money, and at a certain level you can afford to hire people to enforce licensing, not that most companies are willing to risk pirating anyway.

**Comment by DinyaZ** [comment]
I think it is possible to create a compatible product. MS Office vs Libreoffice (https://www.libreoffice.org/) which is full compatible, read and write also the MS Office files, and overall it is a very similar product. (Meanwhile Tb only reads the .vbp files.)
.
From the marketing side, there are products which used or even use the "Vb6" myth and the "Vb6" word in theirs marketing stratetgy. For example:
- XOJO. They write: "Visual Basic (6 or earlier) and Visual Basic .NET use a language very similar to the Xojo language. You will notice that many of the commands are nearly the same, but there are differences as well."
They even developed a migration tool from Vb6 to Xojo
"To help make your transition from Visual Basic easier you can also download the open-source VB library which maps many VB commands to their Xojo equivalents for you:
[Xojo.VB](https://github.com/xojo/VB): A library of Visual Basic functions for use with the Xojo programming language."
And XOJO lives.
.
- B4x: They advertises theirs product already on the main page of theirs website with this: "B4X programming language is a modern version of Visual Basic.". They have official form topics to help the migration."
And B4x lives.
.
.
But as an idea, I think it should bet better to change the TwinBasic name, because the word "TWIN" suggests wrongly that this is a twin=copy of something.

**Comment by JBEJBE** [comment]
VB6 is copyrighted, patented, trademarked intellectual property of MS. Even if not sold anymore, all rights still belong to MS, who invested hundred millions into the product. You can't simply reprogram and resell it, hoping the rights owner looks away silently.

Reprogramming VB6 without consent from MS is risky, but could be succesful. One case in hand is SAS, a very successful statistical software, and its 100% clone WPS. After yearlong legal battles, WPS won the case (Wordwide sales OK, US market forbidden).
On the other hand, the marketing of an IBM operating system/360 clone "Hercules Emulator", which IBM themself open-sourced, was forbidden in court for an interested company. 

So ideal would be a written consent, maybe MS wants a revenue provision. If MS denies the cooperation, the future of TB will most likely be ruled in court with good chances for TB. We may only know after a long time and lots of legal fees. Just warning, that all this needs to be sorted out timely with advice from a good lawyer. Hoping alone won't help us in the long run.

**Comment by DinyaZ** [comment]
> SAS, a very successful statistical software, and its 100% clone WPS.
.
This is not exactly the same, because Vb6 is an abandoned project, and the "clone" wont compete directly with the original. 
.
By the way the first questions to MS in a such discussion: Have you plans in the near term future to develop a 100% Vb6 compatible language and IDE? What do you suggest to the developers who have to maintain old vb6 written projects? Have you plans in the near term future to develop a 100% Vb6 compatible migration tool?
Have you plans to maintain Vb6 support in the Windows11 and its successors? If yes, how long? If no, when will you abandon the Vb6 support?

**Comment by JBEJBE** [comment]
The SAS/WPS case showed, that you can sometimes even reprogram a "living" product, so winning chances for TB seem much higher. Of course will MS ask many hostile questions. But better answering them timely and cost effective outside a court ;-)

**Comment by DinyaZ** [comment]
"> chances"
.
.
A little, intresting detail. On a Microsoft owned and controlled developer forum this question have came up a few times.
.
["https://github.com/twinbasic/twinbasic/issues/1472#issuecomment-1427578488"](https://developercommunity.visualstudio.com/t/support-vb6-programming-and-vba-programming/351655)
.
Scroll down, and look at the very last comment, it is our good old friend, RADbasic Carles who wrote about his intentions to create a follow on VB6 successor. And got nothing from the topic administrator, who was involved in the discussion by the way....

**Comment by kismert1** [comment]
> VB6 is copyrighted, patented, trademarked intellectual property of MS

True. But, let's look at this a little further: 

- US patents tend to run out after 25 years. So, tB is likely in the clear here.
- While "VBA" and "VB6" are certainly trademarked, no one would confuse "twinBASIC" with either of these marks.
- Further, it is OK, (at least in the US) for companies to mention a competitor's mark in advertising, white papers, etc. You can make any number of (factual) claims about your rival's product, and how yours is better. 
- As for copyright, the question would be: is tB using material copyrighted by MS, especially source code? I think a reasonable person would answer "no". The VBA spec is freely available, the tB source is original, and the development platform is completely different.

So, I think tB is in pretty good shape, at least on these points.

PS I'm not a lawyer, but I've watched a lot of "Better Call Saul" episodes.

**Comment by dmrvb** [comment]
In the real world, or maybe the unreal legal world, it does not matter what the truth is, if MS threaten legal action then Wayne (and all of us) is in big trouble.
LibreOffice does a fairly good rip off of MS office, and Office is a current project. tB is a new language that just happens to easily import VB6 code so I think morally we are safe, but who knows.
Anyway, however it goes I do like the idea of getting Saul to help.
and, I reckon RADBasic is sailing a bit closer to the wind.

**Comment by DinyaZ** [comment]
"I reckon RADBasic is sailing a bit closer to the wind."
.
.
I am sorry to say but I have doubts about RADbasic. It doesnt show any visible progress, but 100-110 followers pay on Patreon every month, practically for nothing. Cant understand why it has any followers.

**Comment by mansellan** [comment]
> > VB6 is copyrighted, patented, trademarked intellectual property of MS. Even if not sold anymore, all rights still belong to MS, who invested hundred millions into the product. You can't simply reprogram and resell it, hoping the rights owner looks away silently.
> 
> But those rights don't extend to preventing people from building a product that is compatible with the syntax. For a salient example, look at the recent Oracle vs Google case. Or LibreOffice. The only issues would be is if there's code theft or otherwise distributing the actual property of MS... e.g. tB couldn't distribute the controls that came with VB6, or use the graphics or most other assets from it.
>> Exactly this. Building a compatible product is not IP infringement, as long as the original IP is not infringed. Check out Halt and Catch Fire for a simplified take.
> 
> > I am sorry to say but I have doubts about RADbasic. It doesnt show any visible progress, but 100-110 followers pay on Patreon every month, practically for nothing. Cant understand why it has any followers.
> 
> Unfortunately I have to agree... they were supposed to release a new beta last November to show some progress, but as far as I can tell that hasn't happened (I don't subscribe but asked someone who does), and the last beta before that was maybe 0.01% of the way to full compatibility; I wasn't around here in the early early days but looking back it seems even the earliest public releases of tB were well beyond that, and definitely the ones from that time period. At this point I think the vaporware label is applicable. And while from a technical POV the competition might be nice, a competitor would certainly hurt economic prospects for tB... but from the looks of things right now, it's not a serious contender, so that's good for Wayne and tB.
>> I have to agree. I think Carlos had the right intention, but this is such an immense problem domain it takes someone like Wayne to make it happen.

**Comment by JBEJBE** [comment]
@kismert1: Thank you for your detailed clarification on US laws, I'm more into European laws. All your points are valid and chances for tB of winning a case against MS (US and Europe) seem indeed high. But you never know. One of my concerns is the "100% compatible to VB6 with all its flaws" claim, signalling an excact copy. I personally don't need 100%, maybe this needs to be adressed down the road.

"Better Call Saul" - great, that's basically what I'm trying to signal to Wayne.

@fafalone: Yes, all valid points. Patent cases are complex, everybody relies on technology from others. Though tB goes a little further with it's "100% compatible" claim. But again: waiting paralysed for a case is not a convincing strategy. Better call your lawyer and deescalate as much as possible with MS upfront.

Another point strikes me more. The company organization of tB as a one-man-show needs to be adressed for the reasons made above. When Wayne isn't available for some reason, business needs to go on. So I would love to see a real company behind the product with clear responsibilities. And tB needs more programming power, some things simply take too long, even if Wayne's efforts are close to genius. It may be hard for Wayne to accept this step from one-man-band to a real band, though this evolution will be inevitable, when tB takes off on a bigger scale.

**Comment by fafalone** [comment]
The sense in which tB means 100% compatible though, it 100% compatible with the documented syntax. It won't be compatible with e.g. code that reads the `EXEPROJECTINFO` structure of your exe to get info about the project, because internally tB exes are their own format, not reverse engineered VB6 exes. It doesn't depend on MSVBVM60.DLL, so all the advanced hacks using VB internals based around calling things like `CreateIExprSrvObj` or `VBDllGetClassObject` won't work. 

That makes a difference legally... trying to reverse engineer their code and pass it off as your own is problematic, but being compatible with the publicly documented syntax and APIs is not.

**Comment by JBEJBE** [comment]
@fafalone: I don't think, it's that simple, but I have to leave the deeper explanations to the trusted "Saul" ;-) 

As much as anybody else I do wish, that Wayne succeeds with his vision of a modernized VB6. We need to realize, that tB navigates through a complex legal minefield. MS is known for it's rude business antics. We got to be careful to get it all together right: product, company structure, ledal advice, management, strategy ...

This is a giant undertaking. Many aspiring new companies fail in one or more before mentioned fields. I see our part as a community to give Wayne input on his mission.

To close positive: products like Xojo indicate, that there IS a way though the djungle, though we don't know, if MS tried to stop them, or will stop them. Therefore it's so important, to know the legal view towards tB from MS top management or legal department timely. If MS plans to spoil our party, we need to know.

RADBasic: maybe join forces and create one united product instead of two competing?

**Comment by mburns08109** [comment]
Xojo? (never heard of it until now)

Hmm... interesting.

From: https://documentation.xojo.com/getting_started/introduction/what_is_xojo.html
> Xojo doesn't force you to use a specific OS. Are you a Mac developer that wants to create Windows apps? You can do that with Xojo right from your Mac. Do you use Windows, but want to create Mac apps? You can do that from within Windows. In fact, you can develop using Xojo on Windows, Mac or `Linux to create apps that work on Windows, Mac, Linux or web

So, All the pigs are equal, eh? Ah, but...

> (iOS app development does require a Mac, however).

It appears that some of the pigs are a little more equal than the others, still.

**Comment by DinyaZ** [comment]
> Xojo? (never heard of it until now)
> 
> Hmm... interesting.
> 
> From: https://documentation.xojo.com/getting_started/introduction/what_is_xojo.html
> 
> > Xojo doesn't force you to use a specific OS. Are you a Mac developer that wants to create Windows apps? You can do that with Xojo right from your Mac. Do you use Windows, but want to create Mac apps? You can do that from within Windows. In fact, you can develop using Xojo on Windows, Mac or `Linux to create apps that work on Windows, Mac, Linux or web
> 
> So, All the pigs are equal, eh? Ah, but...
> 
> > (iOS app development does require a Mac, however).
> 
> It appears that some of the pigs are a little more equal than the others, still.
.
I bought Xojo subscription a few years ago, but after a few month I left them. Xojo is not a bad idea, with VB6 like syntax can you develop with fast learning curve even webprojects, and they have cloud servers, so you can launch the webproject directly with one button, and even without any serveradmin knowledge. So this is nice, but the reality was that Xojo made very slow code, and the Xojo IDE was specially slow and buggy, so it was not a viable VB6 alternative. 
The other problem with Xojo that it is expensive, plus with version upgrades they had also compatibility issues.

**Comment by mburns08109** [comment]
More re: XoJo

Also interesting, that they specifically address Access:
https://documentation.xojo.com/topics/migrating_from_other_development_tools/migrating_from_microsoft_access.html

Ok,
> Migrating an Access application is typically a three-step process where you migrate the database itself, the forms that are used to manipulate the data and the source code.

Hmm...
> When migrating a Microsoft Access application, you first need to consider the database. If you are using the Access “Jet” database engine, you will most likely want to migrate it to another database engine. Although you can connect to a Jet database using [ODBC](https://documentation.xojo.com/api/databases/odbcdatabase.html) or ADO on Windows, Jet is not a cross-platform database format. On a Mac you can only connect to a Jet database using ODBC in read-only mode.

...but:
> Access is programmed using the Visual Basic for Applications language which is quite similar to the Xojo programming language. **_You will have to rewrite your code_**, but at the same time will find the Xojo programming language to be familiar in its syntax and commands.

...yeah.

**Comment by mburns08109** [comment]
So it sounds like XoJo will be "jack of all trades" but "master of none" at the same time?
Perhaps and object lesson in there for _**US/tB**_?

**Comment by DinyaZ** [comment]
> Ah...planned
.
.
Yes, it is a promise for long-long years...

**Comment by dmrvb** [comment]
As we are going a bit off-topic...
Xojo (RealBasic) has been around for ages. Like tB its (almost) a one man effort but there are rumours that he does not respond to bug reports as well as Wayne does, and does not allow critical comments on his forum. Its not VB compatible so if a code rewrite is needed then Delphi looks like a much better option. This also targets Apple devices which is a huge bonus. Delphi has been around as long as VB but never quite took off in the same way. There is now a free community version but this is probably too late to make it really popular. Delphi is based on Pascal syntax which I think is not as nice as VB but better than C. If tB fails and if I was ten years younger then Delphi would be my choice.

**Comment by DinyaZ** [comment]
When I was young medical student, I learned the then mainstream Turbo Pascal, it was a handy, late DOS era language. But the Borland did exactly the same what Microsoft did with the VB6 a few years later: Borland came out with Delphi, dropped Pascal without code conversion tool to Delphi, so long, and thanks for all the fish. 
Then I moved to VB.

**Comment by GaryMiller** [comment]
I also passed on Xojo because of speed.  I asked on their forum if there were any benchmarks and somebody wrote a simple benchmark and were shocked at how slow it was.  They had to end up turning all these different kinds of event checking and it finally started to approach reasonable performance.  It did seem like they had a pretty nice user community established though.

**Comment by JBEJBE** [comment]
"If tB fails ..."

tB won't fail. Wayne seems smart enough to make the right moves and decisions.

**Comment by OldestCoderInTown** [comment]
> TB most likely needs to stay closed source, with all inherent downsides. Being a small company is no obstacle. The huge MS company left thousands suddenly stranded on a lonely VB6 beach. Size doesn't matter to me.
