### ISSUE TITLE
Redimmed variant array:  Incorrect additional indexes do not give rise to an error message

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1503]
**Describe the bug**
A dynamic array , created and redimmed to size, allows the inclusion of additional indexes without error when addressing items in the array.  The additional indexes are ignored.

```
Sub test1DArrayWith2DimsRef()

        Dim myA() As Integer
        ReDim myA(3 To 6)
        myA(3, 1) = 10
        myA(4, 2) = 20
        myA(5, 3) = 30
        myA(6, 4, 5, 6) = 40
        
        Debug.Print "Que?"
    End Sub
```
![image](https://user-images.githubusercontent.com/81257042/220090233-1fd44635-293c-4651-96f0-eb058b78d0a3.png)

**Expected behavior**
The compiler should issue a warning if incorrect number of dimensions are used.

**Desktop (please complete the following information):**
 - OS: WIndows11
 - twinBASIC compiler version IDE Beta 251

**Comment by wqweto** [comment]
Btw, in VB6 it's a run-time error 9 `Subscript out of range` i.e. the compiler cannot stop this kind of code from compiling.

**Comment by bclothier** [comment]
Just to illustrate @wqweto 's point:

```
Public Sub ThisIsLame()
    Dim x() As Long
    ReDim x(0 To 1, 2 To 3)
    
    Debug.Print LBound(x), UBound(x)
    
    ReDim x(4 To 5)
    Debug.Print LBound(x), UBound(x)
End Sub
```

This is legal code and will run correctly. tB can potentially do better by doing code path analysis and determining that it's impossible for an array to have a given N dimension at that point but such analysis might take some effort to implement.

**Comment by mburns08109** [comment]
how do C# or vb.net handle this issue? ...any significant differences?

**Comment by mburns08109** [comment]
pfft - I withdraw the question.
I totally forgot this:Array lower bounds can be only '0'
Article
09/15/2021
2 minutes to read
9 contributors
A declaration statement or New clause specifies an array with a lower bound other than 0.

When you create or initialize an array variable, you can optionally specify the upper bound of each dimension. If you do, the length of that dimension becomes the upper bound plus one, because the lower bound is always zero. You can optionally specify the lower bound as well, but you must specify 0. The advantage of doing so is that your code is easier to read.

**Comment by FullValueRider** [comment]
@Mburns08109 Its not about the lower bounds, its about using more dimensions than you specified in the Redim statement.

**Comment by mburns08109** [comment]
@FullValueRider 
Yes...I'm aware.
My question was predicated on running the exact test as shown above. Once I received the lower bounds error, I recalled the discussion where the .Net team had revamped the internals of array handling, eliminating the variable lower bounds in the process. Therefore, the reason for my "does .Net do it the same way" query was thoroughly negated, because the .Net platform internals handles arrays differently than VBx. Hence my subsequent withdrawal of the question. If you prefer, I could do an:
(in my best Emily Litella voice) 
"Oh!...that's very different. ...nevermind"
(/in my best Emily Litella voice)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 256.  Thanks!
