### ISSUE TITLE
a form with a user control cant open form in ide 

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1512]
**Describe the bug**
i have  a problem in the ide  a form with a user control made by me , 
in runtime everything is ok  
but in the ide when i try to reopen the form  i have this screen and if dont close it manually it will never stop looping
cant open the form.

![immagine](https://user-images.githubusercontent.com/124681792/222198450-2dca60d9-5bef-44d4-8276-ccd73e0b4308.png)
 

[TestListBoxColorata_1.zip](https://github.com/twinbasic/twinbasic/files/10863406/TestListBoxColorata_1.zip)

**Comment by marcoslm** [comment]
I also have the same problem since beta 217 (beta 216 works fine for me).

**Comment by bodrusG** [comment]
Unfortunately I tried to go down to 250 and I have the same problem

**Comment by bodrusG** [comment]
i took the code from the twinbasic project, created a project in vb6 and pasted it.
After seeing that it worked I saved the vbp and imported the project into twinbasic.
Now the problem of the form not opening is gone.
Twin Basic 257

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting the problem.  I will look into this tomorrow.

**Comment by WaynePhillipsEA** [comment]
OK, I've reviewed the problem.   It's actually due to code in your project that is causing a stack overflow.  Take this for example:

```
Public Property Let BackColor(v As OLE_COLOR)
    mBackColor = v
    Me.BackColor = mBackColor
    'PropertyChanged "BackColor"
      
End Property
Public Property Get BackColor() As OLE_COLOR
    Return Me.BackColor
End Property
```

Accessing `Me.BackColor` is recursive because it refers to itself.    If you had the equivalent code in a VB6 UserControl (changing the `Return` statement accordingly for VB6 syntax), it would produce an 'Out of stack space' error when you try to use the control on a form.   This happens because the property-get is executed by the IDE/compiler for the property sheet purposes.

Obviously, the hard-crash should not be happening, so I will get that fixed and have it reported as a stack overflow error similar to VB6.   But ultimately, this code needs fixing in your project too.

**Comment by WaynePhillipsEA** [comment]
You will also need to correct the other properties that similarly have recursive problems... FontName, FontSize, FontItalic and FontBold.

**Comment by bodrusG** [comment]
Many thanks for your precise explanation

**Comment by WaynePhillipsEA** [comment]
This issue is now fixed in BETA 259.  Thanks for reporting!
<img width="503" alt="tbNativeExceptions" src="https://user-images.githubusercontent.com/25738109/222708538-6574a047-d6b0-4912-b2ba-be74ae1f047e.png">
