### ISSUE TITLE
File flagged by antivirus engines as potentially malicious

### ISSUE THREAD

**Issue by JPluess** [twinbasic/twinbasic#1574]
Hi there,

I recently uploaded a file to VirusTotal for a scan, and it seems that there are a few red flags raised by the antivirus engines. I assume that it's a false alarm but Avast antivirus also triggered a warning.

I understand that false positives can occur, causing legitimate files to be flagged as potentially harmful. In this case, I kindly request you to review the file.

https://www.virustotal.com/gui/file/d48823d8071ecb95efd20b40e9aeb7d6af3a775aea352de3ee7ea65d54cc1920
![grafik](https://github.com/twinbasic/twinbasic/assets/7995240/c9817518-f2ab-4a44-9911-5ba70f27491f)

**Comment by fafalone** [comment]
There's no real way to avoid this, not for VB, not for tB, or for anything else... 3 detections from obscure engines isn't a worrisome score. Some of these flag any unknown exe, some have pattern matching so vague it's nigh impossible to not match, some pick random APIs to flag... 

Is this something new to the current version or are they all doing this? If it's the latter nothing to be done.

**Comment by WaynePhillipsEA** [comment]
Anti virus software can flag files for viruses for all sorts of reasons.  Yes, unless you're doing something untoward, then it will be a false-positive.  Unfortunately, false positives are largely out of yours, and our, control.

This happens all the time with development tools (e.g. VB6 and VS etc), since the files you are generating have never been seen in the wild before, and so AV vendors typically treat them as suspicious until proven innocent.

I've found that the best way to deal with this is to sign your executables with code signing certificate.  Over time, AVs will start applying reputation to your code signing certificate, and so you'll get fewer false positive detections.

**Comment by sokinkeso** [comment]
It mainly depends on what dll functions your app is using...
Avast (in its latest versions) and Avira, they both show many FALSE-positive scans...
But I agree with Wayne, about signing the app , with code signing certificate from a globally trusted certificate authority (and not a private/custom one)
