### ISSUE TITLE
"Bad DLL definition, stack corruption detected"

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1678]
**Describe the bug**
A while back I made LongLongHelper.dll for VB6, taking advantage of tB's `LongLong` to perform operations on `Currency` in VB6. It works fine in VB6. Today I was testing some DLL search path issues in tB and imported the VB6 test project for it, and got the error in the title. 

**To Reproduce**
Projects attached: Built DLL, source for DLL, working VB6 project, imported not-working tB project.

**Expected behavior**
No error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.386

**Additional context**
Since tB doen't search the app dir I tried adding it, no help. 

[LongLongHelper.zip](https://github.com/twinbasic/twinbasic/files/12525512/LongLongHelper.zip)

**Comment by WaynePhillipsEA** [comment]
Looks like you've changed the `LongLongInc` parameters?  The implementation in the DLL in the root folder of the ZIP doesn't have the `Amount` argument, so the definition in your project does not match (since it does have the extra `Amount` parameter in the Declare definition).

If I rebuild your DLL from source, the built DLL now matches and so works as expected.

**Comment by fafalone** [comment]
But how would it work in VB6 then? It's not just not crashing, it's returning the correct value.

**Comment by WaynePhillipsEA** [comment]
In tB we could ignore it too... but you've corrupted the stack and so it will come back to bite you at some point.  The error message is correct, and you're far better off knowing about the problem.

**Comment by fafalone** [comment]
I see... yes best to just leave it.
