### ISSUE TITLE
Very simple interface implementation works in VB6 but not tB

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1729]
**Describe the bug**
Trying to implement IItemNameLimits:

```
    MIDL_INTERFACE("1df0d7f1-b267-4d28-8b10-12e23202a5c4")
    IItemNameLimits : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE GetValidCharacters( 
            /* [string][out] */ __RPC__deref_out_opt_string LPWSTR *ppwszValidChars,
            /* [string][out] */ __RPC__deref_out_opt_string LPWSTR *ppwszInvalidChars) = 0;
        
        virtual HRESULT STDMETHODCALLTYPE GetMaxLength( 
            /* [string][in] */ __RPC__in_string LPCWSTR pszName,
            /* [out] */ __RPC__out int *piMaxNameLen) = 0;
        
    };
```

oleexp.tlb:

```
[
	odl,
	uuid (1df0d7f1-b267-4d28-8b10-12e23202a5c4)
]
interface IItemNameLimits : stdole.IUnknown {
  HRESULT GetValidCharacters([in, out] LONG *ppwszValidChars,[in, out] LONG *ppwszInvalidChars);
  HRESULT GetMaxLength([in] LONG pszName,[in, out] int *piMaxNameLen);
}
```

Class:

```
Option Explicit

Implements IItemNameLimits

Private Sub IItemNameLimits_GetMaxLength(ByVal pszName As Long, piMaxNameLen As Long)
piMaxNameLen = 2147483647 'MAX_LONG; i.e. no limit
End Sub
Private Sub IItemNameLimits_GetValidCharacters(ppwszValidChars As Long, ppwszInvalidChars As Long)
ppwszValidChars = StrPtr("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyv0123456789")
End Sub
```

```
(af5c.785c): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00df6e6c ebx=019c19e2 ecx=00c300c0 edx=7584f2c0 esi=00e21c71 edi=0093e90c
eip=00c30053 esp=0093e84c ebp=0093e878 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
Project1_win32+0xf0053:
00c30053 0082eec00010    add     byte ptr [edx+1000C0EEh],al ds:002b:8585b3ae=??
```

tB is just restarting from file on crash from the oleexp version that works in VB6. The tbShellLib version, `Private Sub IItemNameLimits_GetMaxLength(ByVal pszName As LongPtr, piMaxNameLen As Long) Implements IItemNameLimits.GetMaxLength` is the line given for the access violation.

**To Reproduce**
 Minimal reproduction attached. Run, click button.

**Expected behavior**
No crash, as per VB6.

**Screenshots**

![image](https://github.com/twinbasic/twinbasic/assets/7834493/fa7e2b3c-f192-4a80-b6ee-3f48618f2e8b)

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - twinBASIC compiler version 0.15.423

**Additional context**
[SHLimitInputEdit.zip](https://github.com/twinbasic/twinbasic/files/13654676/SHLimitInputEdit.zip)

The tbShellLib def of the API needs a ByVal, but it's not used in the VB6 version.

**Comment by fafalone** [comment]
Same thing happens with tbShellLib version in both 32 and 64bit.

64bit gives a different set of errors; I set the disassembly to where the callstack was last in the project's code:

![image](https://github.com/twinbasic/twinbasic/assets/7834493/a58ec221-5b89-4b80-abf3-732ef60a4755)

Looks like an exception triggered by STATUS_HEAP_CORRUPTION.

**Comment by fafalone** [comment]
Still an issue as of Beta 476; I tried the better practices of using StrPtr to a class-level variable and setting the unused pointer to 0, it made no difference. Trace mode provided no help;

```
02:00:34.419
02:00:34.419 │ │ │ │ │ ├ IUnknown::QueryInterface: {object &H00000249EF63D2B0}, iid:={1DF0D7F1-B267-4D28-8B10-12E23202A5C4} (IItemNameLimits)
02:00:34.419
02:00:34.419 │ │ │ │ │ ├ IUnknown::QueryInterface: HRESULT:=S_OK
02:00:34.419
02:00:34.419 │ │ │ │ │ │ ┌ Sub Class1.IItemNameLimits_GetValidCharacters(Me:={object &H00000249EF63D2B0}, ppwszValidChars:=0, ppwszInvalidChars:=6)
02:00:34.419
02:00:34.419 │ │ │ │ │ │ └ Finished in 0ms, HRESULT:=S_OK
02:00:35.263
restarting from MEMORY [C:\tbproj\SHLimitInputEditBugMaster\Project1WDL.twinproj]
```

**Comment by WaynePhillipsEA** [comment]
From the docs for GetValidCharacters:

`If the method returns a success code, the allocated string must be freed using [CoTaskMemFree]. `

Therefore, you need to allocate the string manually using CoTaskMemAlloc, since it's not using BSTRs. Using StrPtr is not valid here.

**Comment by WaynePhillipsEA** [comment]
Another thing, you also need to set `ppwszInvalidChars = 0` explicitly in your `GetValueCharacters` implementation.  It is an out-only parameter and so can contain an uninitialized value on entry to your procedure.

**Comment by fafalone** [comment]
I did trying zeroing the other parameter as per last post, no change, but the issue remains, using StrPtr works in VB6 *every time*, and fails in tB every time. 

I think tB would be seriously limiting compatibility if we took every instance of 'Oh well you're not doing right but VB6 cleans up your stupid mistake' and didn't support it 🤣

**Comment by WaynePhillipsEA** [comment]
Your implementation was wrong.  It is not tB at fault here.   

The code is equally wrong in VB6 -- but for whatever reason it doesn't trigger an **immediate** problem there.    It is not valid to pass a BSTR to CoTaskMemFree directly, and so it will either outright fail, or cause some memory corruption.

BSTRs do actually get allocated with CoTaskMemAlloc deep in the OS, but because of the additional hidden length prefix it is not valid to pass the raw BSTR pointer directly to CoTaskMemFree.

Yes, tB seems to be "more sensitive" than VB6 here.  I haven't looked into the reason behind that, but ultimately bad code needs to be fixed at the source.

**Comment by fafalone** [comment]
That's going to be a *major* caveat to backwards compatibility given the giant mountain of bad code a language aimed at non-professionals has built up. I understand the implementation is wrong, but VB6's behavior here is reliable, and isn't tB supposed to match its quirks? This isn't something that results in trashing the stack making a crash a matter of seconds away. Isn't 'it works in VB6' the standard here? Not 'it works *and* is written perfectly'?

**Comment by fafalone** [comment]
I call it reliable because it repeatedly runs over and over in both pcode and native code, with no crash even the control is destroyed, and the API behaving as expected.

It might be frustrating but even assuming it did lead to a crash once in a while (not zeroing the unused pointer would be in a different class than the string issue here in that regard, assuming VB didn't zero it); I think most people would expect their apps to go ahead and run the several hours or days, or the 99 times out of 100, rather than be told 'oh well maybe there's some minor error somewhere that leads to an issue in an outside caller sometimes, therefore even running at all is outside the scope of compatibility'.

Things that are short-term major issues, sure handle them better, but tB being far less forgiving even in 32bit mode for long term minor issues.... I'm just saying that a lot of people are going to consider it an incompatibility and blame tB if they find their code not running when something works 999 times out of 1000 in VB6 or only might lead to a mysterious crash once in a great while, but *never* works in tB. Then if the response is 'write better code' for things that just work?

**Comment by WaynePhillipsEA** [comment]
If you're using an API incorrectly, then it's _undefined behavior_.  In which case, it might _seem_ to work reliably on your machine, in your conditions, but who knows what will happen on another machine in different conditions (e.g. different OS, different memory pressures, etc).   On other machines it might be as reliable as a chocolate teapot.

Since we can confirm the issue goes away with **_correct_** usage of the API, then I'm certainly **_not_** spending any time looking into what may be the difference here at this time (or any time in the v1.x releases) as there's just too much other important stuff to do.  

For all I know, there could be some big switch deep inside the OS that detects VB6 apps and goes into a special leniant mode... it's a rabbit hole I'm not going to go down at the present time.

**Comment by wqweto** [comment]
@WaynePhillipsEA Btw, in VB6 StrPtr from a string literal directly returns an address from bss (or data?) section of the executable which is r/o blob of length prefixed wchars and apparently never able to be freed so never becomes invalid i.e. address is valid throughout process lifetime. 

I was wondering if TB produces intermediary BSTRs in this case which are immediately freed so that StrPtr result points to invalid memory already inside interface method.

**Comment by WaynePhillipsEA** [comment]
For IDE mode, tB allocates literal BSTRs at compile time, and StrPtr on them should produce static addresses (ie. not temp copies).

For compiled, they are output in the data section, as per Vb6.

**Comment by wqweto** [comment]
If the returned address is not prematurely deallocated it should not AV as long as treated as LPWSTR and provided that CoTaskMemFree can discern if chunk is “owned” by COM allocator i.e. allocated by CoTaskMemAlloc.

I suppose returning static strings from C/C++ or BSTR addresses from VB6 in cases like the above could/should silently be semi-supported by the OS and esp. CoTaskMemFree i.e. if it becomes noop when chunk is unrecognized or outside COM allocator heap no harm is done in using such “static” LPWSTR’s in the long run.
