### ISSUE TITLE
tB doesn't throw error for a Win API procedure that has been misdeclared with extra argument

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1825]
**Describe the bug**
This is the edgiest of an edge case, but I will report it anyway 🙂... 

In 64-bit mode, if user misdeclares a Win API procedure by adding by mistake an extra argument, tB ignores the extra argument at runtime. However, in 32-bit mode, tB warns user by throwing a "Bad DLL Definition" error.

**To Reproduce**
Steps to reproduce the behavior (not specific to CopyMemory, but used by example):

```vba
Private Declare PtrSafe Sub CopyMemory Lib "kernel32.dll" Alias "RtlMoveMemory" ( _ 
    ByRef Destination As Any, _
    ByRef Source As Any, ByVal Length As Long, _
    ByVal superfluous As Long) '<-- added an unsupported argument

Sub test()
    Dim a As Long, b As Long
    a = 1: b = 2
    CopyMemory a, b, 4, 99999 '<-- fails in 32-bit tB with "Bad DLL Definition"
    Debug.Print a 'prints 2 in 64-bit tB
End Sub
```
**Expected behavior**
tB throws a "Bad DLL Definition" in both 32- and 64-bit modes.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC v502

**Comment by WaynePhillipsEA** [comment]
On x86 (32-bit), using typical stdcall calling convention, each parameter occupies space on the stack, which is pushed on to the stack by the caller, and popped off the stack the callee.  It is therefore very easy to detect whether  the passed arguments were 'correct' (in terms of stack size) by checking if the stack position was returned to the expected state after the call was made.

On x64 (64-bit), the calling convention is different in that the first four arguments are passed in registers rather than the stack, and any further arguments are passed on the stack but importantly are NOT popped off the stack by the callee.  It is therefore impossible to know whether the passed arguments were 'correct' in the same way that we can on x86, and therefore this request is just not possible in a generic way.
