### ISSUE TITLE
ActiveX DLL cannot used as Excel automation addin

### ISSUE THREAD

**Issue by loquat** [twinbasic/twinbasic#1875]
1.use default ActiveX DLL template to create a AX DLL project
2.add code below
Module MainModule
    ' This project type is set to 'ActiveX DLL' in the Settings file
    Public Function MyAdd(ByVal a, ByVal b)
        Return a + b
    End Function
End Module
3.save project and compile
4.register that dll manually
5.we click Excel-DevTools-Excel AddIns-Automation(&U), select the compiled dll, my dll xlAutomaion_win32.dll
  it shows Error: The selected file does not contain a new automation server or does not have sufficient permissions to register on the automation service.
  i have run Excel.exe as administrator.

**Comment by GCuser99** [comment]
You can access your ActiveX DLL by going to Developer tab, Tools->References and then scroll until you find xlAutomation. Check on that and then you can access the function from your VBA code. If you want an Addin, then try Sample 5.

**Comment by loquat** [comment]
> You can access your ActiveX DLL by going to Developer tab, Tools->References and then scroll until you find xlAutomation. Check on that and then you can access the function from your VBA code. If you want a COM Addin, then try Sample 5.
Excel automation addin is an ax dll to add user define formula functions which can call in worksheet.
which is different from VBA VBE addin as well as Com AddIn

**Comment by mwolfe02** [comment]
I believe what you are looking for is how to create an [XLL add-in](https://learn.microsoft.com/en-us/office/client-developer/excel/developing-excel-xlls).

If that's the case, I'd consider this a feature request rather than a bug report.  

A few thoughts:

- This would be a **great** feature!
- This won't be a v1 feature.
- It may already be possible to create an Excel XLL given twinBASIC's current capabilities, but exposing and implementing the [required features](https://learn.microsoft.com/en-us/office/client-developer/excel/creating-xlls#turning-dlls-into-xlls-add-in-manager-interface-functions) is beyond my level of technical skill (maybe @fafalone could assist?).
- There's an existing open-source .NET project that could be referenced for inspiration: [ExcelDNA](https://github.com/Excel-DNA/ExcelDna)

Ultimately, twinBASIC may already support this feature, it's just that implementing it requires a good bit of low-level C and C++ knowledge.   

I will be following this thread with great interest.

**Comment by fafalone** [comment]
I'll have to look at it in more detail but it lists a file as required code with this:

`int _cdecl Excel12(int xlfn, LPXLOPER12 operRes, int count, ...)`

Vararg (...) functions are not currently supported in tB with no workaround besides assembly thunks, which are beyond my skillset.

Excel really has no other way to link up formulas and user code? Like it's impossible to go from the worksheet, call a VBA function, which then uses a simple `Declare Function` call into the DLL?

Excepting the potential vararg issue it's likely possible, but would be *a lot* of work. Even if I was able to do it as a proof of concept, I don't know how useful it would be when it looks like the main structure used for passing data back and forth (XLOPER12) would have to be implemented as nothing but a raw byte array where you constantly have to figure out the right offsets to copy data to/from; since sadly tB still also lacks support for unions and subtypes. 

Look at this mess:

```
typedef struct xloper12 
{
	union 
	{
		double num;				       	/* xltypeNum */
		XCHAR *str;				       	/* xltypeStr */
		BOOL xbool;				       	/* xltypeBool */
		int err;				       	/* xltypeErr */
		int w;
		struct 
		{
			WORD count;			       	/* always = 1 */
			XLREF12 ref;
		} sref;						/* xltypeSRef */
		struct 
		{
			XLMREF12 *lpmref;
			IDSHEET idSheet;
		} mref;						/* xltypeRef */
		struct 
		{
			struct xloper12 *lparray;
			RW rows;
			COL columns;
		} array;					/* xltypeMulti */
		struct 
		{
			union
			{
				int level;			/* xlflowRestart */
				int tbctrl;			/* xlflowPause */
				IDSHEET idSheet;		/* xlflowGoto */
			} valflow;
			RW rw;				       	/* xlflowGoto */
			COL col;			       	/* xlflowGoto */
			BYTE xlflow;
		} flow;						/* xltypeFlow */
		struct
		{
			union
			{
				BYTE *lpbData;			/* data passed to XL */
				HANDLE hdata;			/* data returned from XL */
			} h;
			long cbData;
		} bigdata;					/* xltypeBigData */
	} val;
	DWORD xltype;
} XLOPER12, *LPXLOPER12;
```

Now obviously a more friendly wrapper can be made, but that's well beyond the time commitment I'd be able to offer out of my hobby time :)

**Comment by GCuser99** [comment]
Com' on Jon, you should be able to do that in your sleep!

What's interesting is that [in this issue](https://github.com/twinbasic/twinbasic/issues/1860#issuecomment-2157137365) the @forliny provides a VB6 project and shows that the resulting DLL works as an Excel Automation Addin (supports worksheets UDFs). The tB version which had some import errors did not work. Maybe there are clues to find there (way above my pay grade).

**Comment by forliny** [comment]
VB6 ActiveX UDF is different from XLL UDF, 

VB6 UDF uses
Application..AddIns.Add FileName:="MyComAddin. MyUDF ", install UDF
Application..AddIns("MyComAddin.MyUDF"). Installed = True ， Load UDF

XLL UDF uses Application Register XLL "XLLFilePath" to register and load XLL UDF
 
The difference here is unclear.

**Comment by forliny** [comment]
ActiveX DLL  OR XLL ？Haha, looking forward to it

**Comment by loquat** [comment]
waiting for it haha...

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 593.  Thanks
