### ISSUE TITLE
VBA.Collection internal structure compatibility

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#199]
**Describe the bug**
There is no natural way to get the key by index or to get the index by key in a VBA.Collection.
Thus some folks access the internal structure of the VBA.Collection to get to this.
In VBx (VBA and VB6) the internal structure is equal but does not seem to match to tB.

**To Reproduce**
```
Module ModHelloWorld

    Public Sub Main()
        Dim MyColl As New Collection
        
        MyColl.Add "item1", "mykey1"
        MyColl.Add "item2", "mykey2"
        MyColl.Add "item3", "mykey3"
        
        MsgBox CollGetIndex(MyColl, "mykey3") ' should return 3
        MsgBox CollGetKey(MyColl, 2) ' should return 'mykey2'
    End Sub

End Module

Module CollectionHandle
Option Explicit
Private Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (ByRef Dest As Any, ByRef Source As Any, Optional ByVal Bytes As Long = 4)

Public Function CollGetKey(ByVal Coll As Collection, ByVal Index As Long) As String
Dim Ptr As Long, i As Long
Dim sKey As String
If Coll Is Nothing Then
    Err.Raise Number:=1, Description:="Collection not set"
Else
    Select Case Index
        Case Is < 1, Is > Coll.Count
            Err.Raise Number:=2, Description:="Index out of range"
        Case Is <= Coll.Count / 2
            CopyMemory Ptr, ByVal UnsignedAdd(ObjPtr(Coll), 24)
            For i = 2 To Index
                CopyMemory Ptr, ByVal UnsignedAdd(Ptr, 24)
            Next i
        Case Else
            CopyMemory Ptr, ByVal UnsignedAdd(ObjPtr(Coll), 28)
            For i = Coll.Count - 1 To Index Step -1
                CopyMemory Ptr, ByVal UnsignedAdd(Ptr, 20)
            Next i
    End Select
    i = StrPtr(sKey)
    CopyMemory ByVal VarPtr(sKey), ByVal UnsignedAdd(Ptr, 16)
    CollGetKey = sKey
    CopyMemory ByVal VarPtr(sKey), i
End If
End Function

Public Function CollGetIndex(ByVal Coll As Collection, ByVal Key As String, Optional ByVal Compare As VbCompareMethod = vbTextCompare) As Long
Dim Ptr As Long
Dim sKey As String, aKey As Long
If Coll Is Nothing Then
    Err.Raise Number:=1, Description:="Collection not set"
Else
    If Coll.Count > 0 Then
        aKey = StrPtr(sKey)
        CopyMemory Ptr, ByVal UnsignedAdd(ObjPtr(Coll), 24)
        CollGetIndex = 1
        Do
            CopyMemory ByVal VarPtr(sKey), ByVal UnsignedAdd(Ptr, 16)
            If StrComp(Key, sKey, Compare) = 0 Then Exit Do
            CollGetIndex = CollGetIndex + 1
            CopyMemory Ptr, ByVal UnsignedAdd(Ptr, 24)
        Loop Until Ptr = 0
        CopyMemory ByVal VarPtr(sKey), aKey
        End If
        If Ptr = 0 Then CollGetIndex = 0
    End If
End Function

Public Function UnsignedAdd(ByVal Start As Long, ByVal Incr As Long) As Long
UnsignedAdd = ((Start Xor &H80000000) + Incr) Xor &H80000000
End Function

End Module
```

**Expected behavior**
That the location (offsets) of the internal variables match to the VBA.Collection in VBx.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.1168]

**Additional context**
Don't know if this falls under the category "100% compatibility" as it's clear that not every hack shall/can be supported at the end. But I leave this decision to you. Thanks

**Comment by wqweto** [comment]
I've been using [`CollectionAllKeys` implementation](https://github.com/Unicontsoft/UcsFiscalPrinters/blob/master/src/Shared/mdJson.bas#L1399-L1486) for quite some time now.

In the linked repo there are enums with internal offsets of the Collection's private data for x86 and x64 impl.

**Comment by mwolfe02** [comment]
I don't think it would be breaking the 100% compatibility goal if tB does not match _implementation-specific_ details of VB6/VBA.  The [VBA Language Specification](https://docs.microsoft.com/en-us/openspecs/microsoft_general_purpose_programming_languages/MS-VBAL/d5418146-0bd2-45eb-9c7a-fd9502722c74) seems like it would be a good measuring stick in terms of what constitutes 100% compatibility:

> Specifies the VBA Language, which defines the implementation-independent and operating system-independent programming language that is required to be supported by all conforming VBA implementations. This specification also defines all features and behaviors of the language that are required to exist and behave identically in all conforming implementations.

As for the [Collection object](https://docs.microsoft.com/en-us/openspecs/microsoft_general_purpose_programming_languages/ms-vbal/31ec9e63-f71e-4521-863b-a7d12007b7cc), the specification says nothing about how the object should be implemented in memory:

> The Collection class defines the **behavior** of a collection, which represents a sequence of values. 

There are separate entries for each method and property of the Collection object:

![image](https://user-images.githubusercontent.com/305213/121189060-bc217d80-c837-11eb-9cb1-1d20f7985c08.png)

Undocumented features of any programming language should always be considered, "Use at your own risk."  And one of those risks is that the specific implementation of a feature could change.  Heck, a new version of VBA could change the internal implementation of the Collection object and I would not consider that a breaking change, even though it might break code that relied on it.

All that said, I really like Wayne's 3-part test for supporting implementation details that go beyond simply matching the VBA/VB6 language specification. 

As for this particular hack, I've personally never used it (I've tended to use dictionaries if I needed to get at the key values themselves).  But it would not surprise me to learn that there is a sizeable portion of the VB6/VBA community that has used it.

**Comment by bclothier** [comment]
FWIW, I do believe that one factor that makes a programming language such as VB* fall into "most dreaded" category is whenever they make use of hacks or clever code. The idea of refactoring and writing unit test wasn't really a thing back during 90s and as a result, the code tends to be very brittle and very much coupled. I do _not_ want to carry that mentality forward into twinBASIC. 

For that reason, I'd be in favor of encouraging people to refactor the code when modernizing it, which kind of conflicts with the compatibility goal. If the documented features are already hackish, how more hackish will be the support for hacks that breaks the encapsulation of the standard library? 

My concern is primarily that those hacks would then either be left in the codebase instead of being refactored out or even worse is re-used/expanded to infect the rest of the new development. The latter scenario is not one I want to see happening. That said, I do recognize the paradox of needing to allow the legacy code to run so that unit tests can be then written for it, then it can be safely refactored out without breaking the functionality. 

With that in mind, I think the option 2 is a good candidate for subtly hinting that hacks should be substituted. In this particular case, it should be trivial to modify the function that directly access the internal memory structure to use the new tB features and thus allow the call sites to remain unaltered with same behavior. We gain far more idiomatic and readable change as the result. Not all hacks may be that easily mended, but I think that's the general goal we should encourage as part of migration.

**Comment by mwolfe02** [comment]
To @bclothier's point, I favor eventual support for an `Option Strict`*-like directive that would raise compile errors for valid VBA/VB6 code that we want to discourage (such as DefType statements).  There could be a setting to add this directive by default to new code, similar to the way the VBIDE can be set to add `Option Explicit` to new modules.

* The actual directive should be named something other than `Option Strict.`  I don't know what I would suggest off the top of my head; naming is hard.

**Comment by bclothier** [comment]
`Option Just Say No To Hacks`?
`Option Hacks Are Bad For Your Brain`? 
`Option Disallow Hacks`?
`Option Do Not Write Clever Code`? 
`Option Psychotic Ax Murderer`? 
`Option Four Horsemen Of Apocalypse`? 


*ahem*

Jesting aside. Just to link the issue about legacy mode here: #65. Though this is more about disabling the tB features and enforcing the VB* quirkiness, it makes sense to have them handled:

A possible (sane!) candidate would be:
`Option Legacy Disable` (disables the legacy features)
`Option Legacy Enforce` (enables the legacy as discussed in #65 ) 
`Option Legacy Allow` (the default if there is no such statement in a module)

As Mike mentions, the `Option Legacy Disable` could be on by default and added to every new file created to encourage best practices. Importing a old file will not be a problem since the absence of such statement will be same as `Option Legacy Allow`. That way we have a good default toward promoting good coding practices but not making it unnecessarily hard/painful to port legacy code.

**Comment by Kr00l** [comment]
For 2) I would vote for two new props in the Collection object:
`.ItemIndex(Key As String) As Long`
`.ItemKey(Index As Long) As Key`

The case sensivity for .ItemIndex(Key) should be the same rule as for accessing an .Item() by it's "key index".

While at it. Also an `.Exists(Index As Variant) As Boolean` function would be handy.

**Comment by Kr00l** [comment]
It cannot be expected that the internals will be the same for this hack.. I guess that's not practical, thus I close.

The Collection received already additions and I think the below addition might be added as well ?
```
.ItemIndex(Key As String) As Long ' Get ordinal index from given key string
.ItemKey(Index As Long) As String ' Get key string from given ordinal index
```

**Comment by mansellan** [comment]
@Kr00l I just downloaded Beata 349, it doesn't look like these are added yet, unless I'm doing something wrong?

If not, given that these don't exist in VBx, it seems like a great opportunity to follow the VB.Net prior art? They tend to use:

`IndexOf(Key As String) As Long`

There's no equivalent for keys - the VB.Net `Collection` type is more permissive than normal .Net generics, as it's there to ease migration from VB6. However, extrapolating from the above, it seems like

`KeyOf(Index As Long) As String` would be a good fit?

(not trying to nettify twinBASIC, it just seems that as this is new functionality, there isn't a strong argument not to follow prior art. It might help VB.Net users so long as there's no other downsides?)
