### ISSUE TITLE
Discussion: How closely should twinBASIC follow VB.Net syntax for new features?

### ISSUE THREAD

**Issue by mansellan** [twinbasic/twinbasic#36]
Per title really.

Pros: Many VB developers are familiar with VB.Net, easing adoption
Cons: Some VB.Net syntax is a little clunky

**Comment by bclothier** [comment]
My inclination is this:

* Borrow only good bits
* Forget the rest

twinBASIC is unmanaged and should stay that way. Therefore, it need not worry about being too much like VB.NET. I question the utility of supporting compatibility since this requires working with .NET and that's not in the focus here. I mention this because I believe a number of VB.NET features is directly tied to .NET and thus may not apply or translate as well.

I will admit I don't use VB.NET a lot but from what I've seen, VB.NET is not very well-thought well in the language design and I would not want tB to accidentally evolve into VB.NET, even if only considering the syntax and not the framework. Designing a good language is _hard_ and tB has a challenge since it need to be back-compat with VB6/VBA with all its ugly warts. It should not sprout any new wart as a result. :)

**Comment by WaynePhillipsEA** [comment]
In my view, the paramount concern has to be the backwards compatibility with VB6, VBA and ultimately COM.  New features can be considered, but they must not affect or conflict with the backwards compatibility pledge.  As an example, .NETs garbage collection is an absolute no-go, as COM just doesn't play well in that world.

If we can cherry-pick the best bits from VB.NET and other languages whilst keeping things "basic", then great and I will certainly be listening to all ideas put forward.

**Comment by mansellan** [comment]
Sorry yes, I just meant the syntax side of things, not the actual features.

**Comment by WaynePhillipsEA** [comment]
Ah right, sorry, gotcha.  Syntax wise, if there's good reason NOT to copy VB.NET for some feature, then I'm personally fine with that.  As @bclothier says, we don't want tB to become the next VB.NET.

**Comment by bclothier** [comment]
I think [this rant from Mike Wolfe toward the end of article](https://nolongerset.com/new-syntax-in-twinbasic-part-3/) is a thought to take in, especially in the light of the discussion around the #34 for supporting the `out` keyword.

In my personal opinion, a language ought to strive to be:

1) correct
2) easy to read and understand
3) has only one way of doing things. 
4) easy to refactor

**Correctness**

By "correct", I mean that the program can guarantee to do things that are defined. There should be no undefined behaviors. It should not permit nonsense. For example, this is legal code that will compile and run but is nonsense:

```
Dim foo As Something
foo.DoIt()
```

This will compile in VBA and VB6 but it _should not_! The `foo` is unassigned so what could `foo.DoIt()` possibly mean? A good compiler should be able to catch that and warn of such nonsense. Compile-time errors are far easier to fix than runtime errors. Therefore, the more compile-time checks there are, the more likely the program will be "correct". This will not protect the programmer from making logic errors but at least the programmer will get to focus on the logic itself and not the semantics.

After all, that's what made VB so popular -- it freed the programmers from the tedious plumbing associated with memory management that C/C++ required and thus was easier to write a more "correct" program compared to doing it in C/C++. That has immense value because the bugs now are about the business logic rather than one-off mistake, null pointer reference, or other such things that has nothing to do with the business problem being solved. But since then it has stood still while other languages such as C# has beefed up on compile-time check and converting more and more runtime errors into compile-time errors.

**Ease of readability**

Many many programming languages focus on being terse, some to point of being effectively a **W**rite **O**nce, **R**ead **N**ever code. Nobody will ever be satisfied with whether a language is not too terse but still expressive. Basic does pretty good of being readable, but we should want to do better and promote code that is readable over "clever code". I think [Mike Wolfe has a good write up on the downside of being too clever](https://nolongerset.com/short-circuiting-vba/). VBA and VB6 in particular suffer from having too much clever code and we do want to avoid clever code that actually harms the readability. Likewise, we should avoid code that says one thing but does something else. Default member access is a prime example:

```
Dim con1 As ADODB.Connection
Dim con2 As ADODB.Connection

con1.ConnectionString = "...."
con1.Open

con2 = con1
con2.Execute "SELECT 1;"
```

This code is kind of misleading because at first glance it _looks_ like `con2` is a copy of `con1` but in fact the absence of `Set` keyword means that the expression `con2 = con1` is actually `con2.ConnectionString = con1.ConnectionString`. Not the same thing that was read! Those kind of code are bad for readability and we want to avoid this.
 
**One way of doing things**

Often, there are several things to do same thing. A good example would be:

```
a = a + 1
a++
```
Both does the same thing (e.g. increment a value in a variable). In this specific example, the difference is arguably over readability or terseness. However, often the variants are not equal. A good example would be the `If` vs. `IIf()` (sticking to VB6/VBA):
```
Debug.Print IIf(True, True, 1/0)

If True Then
  Debug.Print True
Else
  Debug.Print 1/0
End If
```

Obviously, both behave differently. But this should beg a question -- should the programmer even have to choose between the two alternatives? Should the reader know about all possible variants of doing something? Those impact the readability and increase the cognitive load placed on the programmer & reader in parsing the meaning behind the code.

In this case, tB is constrained by the need to be backward compatible with VBA & VB6 so we cannot do too much about that part. However, it still can be managed. For example, by turning on `Option Strict`(c.f. #33 ) and maybe even `Option Disallow Archaic Syntax` to suppress bad choices like `GoSub`, `DefType`, and so forth, that can help with mitigate the bad efforts and allow the programmer to evolve the codebase to a better form that's readable and maintainable. Imagine the compiler warning or erring on a single line `If` statement, which would also handle this dastardly code:

```
Public Sub LookMaNoEndIf()
  If a Then:
End Sub
```

Which leads into the next point...

**Refactorability**

Technically speaking this is not a language feature. This is actually an IDE feature but it is crucial feature and directly impacts how the language features will be adopted and used. With VB6/VBA code, the approach has been among the lines of "Don't touch it. It's been working for N years. It's ugly but it does the job." That actively hinders the ability to progressively improve the code and pay off the technical debt accrued on the codebase. That also means new features will not be adopted even if they could have improved the readability, removed undefined behaviors and prevent errors (especially runtime errors). In an ideal world, we should be able to do something like:

1) Import a VB6/VBA project into twinBASIC
2) Generate a set of unit tests to assert the current behavior
3) Start refactoring
4) Prove the refactoring preserves the original behavior
5) Start add new features or enhancements and write new unit tests

The ability to edit & continue has immense value in helping debugging and developing but this works very well for new development. For fixing bugs, unit tests start to win out. Here, twinBASIC has one **huge** advantage... being COM based, everything is... _interfaces_. That means writing unit tests is much easier and there is a great opportunity to support this and enable the codebase to evolve beyond the "if it's not broken, don't fix it" mentality and making programming fun again. 😄

**Comment by mansellan** [comment]
Some thoughts on "One way of doing things":

C# has many ways of doing things, but the main reason for this is that the language is now ~20 years old. It needs to retain source-level compatibility between versions (so you don't have to rewrite code for every version change), but as time progresses, better syntactical forms are invented. They pile up. In theory, it should be possible to take source code written for C# 1 and compile it in VS2019 (caveat, not tried!).

tB has to maintain compatibility with VB6, that's imperative. But it should also be able to evolve, which may mean allowing terser syntax which equates to more verbose legacy form. I think that's acceptable. The interesting question will be: "what happens when tB needs to support it's _own_ legacy syntax?". IMO the best pre-emptive is to assimilate current best-practice from other modern languages, to defer that problem as far into the future as possible.

**Comment by Greedquest** [comment]
Some more inspirational food for thought on language design; the [Zen of Python](https://www.python.org/dev/peps/pep-0020/#id2)

**Comment by mansellan** [comment]
should probably move to lang-design

**Comment by bclothier** [comment]
TBH, I am more inclined to close this because this ended up as one of sparks for the guiding principles thread that was made and because ultimately it isn’t a really actionable item. Unless I hear otherwise from others, I will close this.

**Comment by WaynePhillipsEA** [comment]
Agreed, this should now be closed.  Thanks all.
