### ISSUE TITLE
Err.Description doesn't make it through to a compiled DLL

### ISSUE THREAD

**Issue by Greedquest** [twinbasic/twinbasic#464]
**Describe the bug**

**To Reproduce**
```vba
Public Class Foo
    Public Sub t()
        Err.Raise vbObjectError + 5, Description:="No project found with that name"
    End Sub
End Class
```

**Expected behavior**
Called from tB we get

![image](https://user-images.githubusercontent.com/25348920/136613265-ae45662b-42af-4612-aa8c-27dfc89f9ba1.png)

as expected.

In VBA we get:
![image](https://user-images.githubusercontent.com/25348920/136613342-d3a25c77-8c51-4959-9297-863ea51aac4d.png)

... which is the default message for that error number `Error$(vbObjectError + 5)`

**Desktop (please complete the following information):**

 - Version: 0.10.5788
 - Win 10

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.   There's a little bit of work to be done on error handling in #56 soon, and so this will be remedied at that point.

**Comment by GCuser99** [comment]
I'll just add that when I compile the below into an ActiveX DLL (v334), calling the ```TestErrChild()``` does raise the error properly, but calling it indirectly through ```TestErrParent()``` returns ```incorrect function``` for the error description.
```
Public Sub TestErrParent()
    Call TestErrChild
End Sub

Public Sub TestErrChild()
    Err.Raise 1, "somewhere", "error raised in child sub"
End Sub
```
Also, if ```TestErrChild()``` is rejiggered into a function instead of a sub, running ```TestErrParent()``` does not raise ANY error, and returns False in the MsgBox:
```
Public Sub TestErrParent()
    MsgBox TestErrChild() ' this displays "False"
End Sub

Public Function TestErrChild() As Boolean
    Err.Raise 1, "somewhere", "error raised in child function" 'no error is raised.
    TestErrChild = True
End Function
```
I've got another Err.Raise issue in my code that actually returns ```Runtime error 91: Object variable or with block variable not set``` but as of yet I have not been able to replicate it in a simple test as above - but hoping that it's related... If you need to see that one I can provide the tB project.

Thanks!

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 411.  Thanks
