### ISSUE TITLE
Support for VB forms

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#567]
This issue is for tracking the status of support for classic VB forms in twinBASIC.

### This feature is not yet implemented.  We hope to have the first beta version of this feature available on 8th February 2022.

This issue is specifically for tracking the support of the base Form, and all the base controls (CommandButton, Label, etc).

**Comment by KarlSevenSeven** [comment]
Perhaps this could be split into 2 stages.
1st stage supports the basic form only.
2nd stage is about the controls then.

Why?
After 1st stage, the VBCCR controls could be used.
Why re-invent the wheel when such controls are already available?
They offer all what's necessary for Windows.

@Krool
This would require PictureBox And Image to be added.

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven, as far as I know, VBCCR is currently 32-bit only, and requires UserControl/ActiveX control support.

**Comment by Kr00l** [comment]
> @KarlSevenSeven, as far as I know, VBCCR is currently 32-bit only, and requires UserControl/ActiveX control support.

I guess he meant that a tB vb-form can use a VB6 compiled VBCCR OCX.
And that shall be the goal in the first phase?
Of course it would be super to re-compile VBCCR one day in future as 64bit in tB.

**Comment by WaynePhillipsEA** [comment]
> > @KarlSevenSeven, as far as I know, VBCCR is currently 32-bit only, and requires UserControl/ActiveX control support.
> 
> I guess he meant that a tB vb-form can use a VB6 compiled VBCCR OCX. And that shall be the goal in the first phase? Of course it would be super to re-compile VBCCR one day in future as 64bit in tB.

Indeed; my point was that it's not just as easy as getting the form implemented... it requires the ActiveX/OCX container control support (which is not as easy as it sounds), and even then it would be limited to 32-bit only due to VBCCR.    The OCX container support will come with the base controls support;  they're likely to be delivered at roughly the same time.

**Comment by bclothier** [comment]
My number one concern is whether we can set it up in such way that the ActiveX controls can be used without requiring registration. The ActiveX has a bad reputation of being unwieldy to work since it requires installation & registration and spawning all kind of DLL Hell due to being registry-centric. If tB ActiveX forms are able to use 3rd party OCX controls simply by having it in a certain subfolder without any references to the registry, that would definitely be fantastic. Office365 has basically solved this by virtualizing the entire registry & filesystem.

**Comment by WaynePhillipsEA** [comment]
@bclothier probably, yes (though some wont be compatible that way).  For VBCCR, I expect so.

**Comment by bclothier** [comment]
I think that as long we are able to handle all the controls shipped by Microsoft, that would be fantastic as that would maximize the backward compatibility and make it easier to migrate any existing codebase that was relying on the Microsoft-shipped controls. Any additional ActiveX controls that are compatible and can be loaded reg-free, would be gravy, I think. 

I do not know enough about VBCCR to know whether the same codebase can use VBCCR instead of Microsoft-shipped controls without any code changes.

**Comment by Kr00l** [comment]
I use all kind of Ax-DLL and OCX reg-free in VB6. It's just the developer machine that has to register them..
Then on a terminal server where users run the app it works reg-free. (via manifest)

**Comment by bclothier** [comment]
@Kr00l I should have clarified. When I expressed that concern, I was thinking of things like add-ins which do not allow for manifest files solution to work well because it's a in-process DLL, not an EXE.

**Comment by Kr00l** [comment]
> @Kr00l I should have clarified. When I expressed that concern, I was thinking of things like add-ins which do not allow for manifest file solution to work well because it's an in-process DLL, not an EXE.

Didn't try but the add-in Dll can use RT_MANIFEST/2 ?

_Process manifests, with ID CREATEPROCESS_MANIFEST_RESOURCE_ID (1), used during process creation,
Isolation-Aware manifests, with ID ISOLATIONAWARE_MANIFEST_RESOURCE_ID (2), used during DLL loading._

**Comment by bclothier** [comment]
I assume this relates to [this article](https://docs.microsoft.com/en-us/windows/win32/sbscs/isolating-components). Reading quickly, I think that wasn't a solution with a .NET-based addins because it requires that one compiles in correct flags and call activation context which .NET does not handle. It would be up to tB to handle that and therefore enable that to make it easy to create an addin that can be isolated and therefore use manifests for DLL files.

**Comment by Kr00l** [comment]
> I assume this relates to [this article](https://docs.microsoft.com/en-us/windows/win32/sbscs/isolating-components). Reading quickly, I think that wasn't a solution with a .NET-based addins because it requires that one compiles in correct flags and call activation context which .NET does not handle. It would be up to tB to handle that and therefore enable that to make it easy to create an addin that can be isolated and therefore use manifests for DLL files.

Ok, as said - never tried it. But sounds true.

So tB would need to allow compilation with `-DISOLATION_AWARE_ENABLED` flag somehow to address this?

**Comment by bclothier** [comment]
I think so and also provide the necessary manifest so that it's available when DLL loads. I have never seen a manifest for a DLL file, and I'm under the impression (which may be mistaken) that it must be embedded for it to work. 

There's also [callback for hosted scenario](https://docs.microsoft.com/en-us/windows/win32/sbscs/using-callbacks-from-hosted-components) that may be more appropriate especially since that we do not own the Office add-in system and must work with it. 

All in all, this seems solvable; tB just needs to provide the necessary supports so that it's easy to generate such DLLs without worrying about the EXEs that hosts it and guarantee that it has all the references it needs to function properly without consulting the registry.

**Comment by Kr00l** [comment]
> I think so and also provide the necessary manifest so that it's available when DLL loads. I have never seen a manifest for a DLL file, and I'm under the impression (which may be mistaken) that it must be embedded for it to work.
> 
> There's also [callback for hosted scenario](https://docs.microsoft.com/en-us/windows/win32/sbscs/using-callbacks-from-hosted-components) that may be more appropriate especially since that we do not own the Office add-in system and must work with it.
> 
> All in all, this seems solvable; tB just needs to provide the necessary supports so that it's easy to generate such DLLs without worrying about the EXEs that hosts it and guarantee that it has all the references it needs to function properly without consulting the registry.

I opened new feature request #569 to "isolate" this. :)

**Comment by bclothier** [comment]
A follow up question for Wayne:

Ought we consider support for the MS Forms 2.0 library and if so would that be a separate issue? I have no idea how much common a VB 6.0 Form and MS Forms 2.0 UserForm share. However, if it is the case that MS Forms 2.0 is quite different, it might be good to consider whether in future we want to support migrating from VBA projects containing userforms to the equivalent forms in tB. 

I also observer that simply referencing MS Forms 2.0 is not sufficient to be able to use it since the expectation seems to be that the project ought to generate its own private type library implementing the UserForm. Again, I don't know if VB forms works similarly but if it doesn't, we should ask whether we want to support creating userforms. 

if there's merits, we can open a separate issue but wanted to ask in case it can be easily rolled into this scope for the VB form support. The ability to migrate VBA userforms will be very valuable, I think.

**Comment by WaynePhillipsEA** [comment]
I think UserForms should indeed be considered separately.  I have to admit that I don't use UserForms much.  I'm sure there is lots of overlap with VB6 forms, but I remember how quirky the UserForms implementation is from when we were looking at the runtime type library generation of them in RD... so it probably needs further consideration.  I agree though, it would be nice to be able to import VBA UserForms into tB eventually.

**Comment by bclothier** [comment]
Opened #584 to track the question of userforms.

**Comment by WaynePhillipsEA** [comment]
Thanks!

**Comment by WaynePhillipsEA** [comment]
We have #706 that covers this in more detail.  Let's now close this issue.  Thanks.
