### ISSUE TITLE
Len(Of ...) vs Len

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#596]
In many languages you can get the size of a datatype without needing to create a value of that datatype (whether it be a native type like LongPtr, or a custom UDT).  VBx only provides Len/LenB that takes a value as its argument:

```
Dim myPointer As LongPtr
Debug.print "Len(myPointer): ", Len(myPointer)

Dim myUDT As SomeUDT
Debug.print "LenB(myUDT): ", LenB(myUDT)
```
It would be nice for there to be a generics version that allows passing just a datatype:
```
Debug.print "Len(Of LongPtr): ", Len(Of LongPtr)
Debug.print "LenB(Of SomeUDT): ", LenB(Of SomeUDT)
```

**Comment by bclothier** [comment]
Just to consider for the matter of consistency.

If we implement the equivalent of [`nameof` operator](https://github.com/WaynePhillipsEA/twinbasic/issues/15#issuecomment-820370079), wouldn't it be more consistent to have a `LenOf()` and `LenBOf()`? Alternatively, we can have `Name(Of <type>)` but then someone will wonder why can't they do a `Name(foo)`. They wouldn't wonder if it's simply `NameOf` and consequently `LenOf` or `LenBOf`, all which must take a type as an argument. I don't think we have to use `Of` just to use a type and besides it would overload the meaning of the `Of` keyword (e.g. closing a generic vs. a type parameter).

**Comment by WaynePhillipsEA** [comment]
> Just to consider for the matter of consistency.
> 
> If we implement the equivalent of [`nameof` operator](https://github.com/WaynePhillipsEA/twinbasic/issues/15#issuecomment-820370079), wouldn't it be more consistent to have a `LenOf()` and `LenBOf()`? Alternatively, we can have `Name(Of <type>)` but then someone will wonder why can't they do a `Name(foo)`. They wouldn't wonder if it's simply `NameOf` and consequently `LenOf` or `LenBOf`, all which must take a type as an argument. I don't think we have to use `Of` just to use a type and besides it would overload the meaning of the `Of` keyword (e.g. closing a generic vs. a type parameter).

There is currently no precedent for passing a datatype directly as an argument... except in generics, hence my reasoning here.

It wouldn't overload the meaning at all, as this would be implemented as a generic.  In fact we can already implement it exactly in twinBASIC:

```
    Public Function MyLen(Of T)()
        Dim value As T
        Return Len(value)
    End Function
    
    Public Sub Test()
        MsgBox MyLen(Of LongPtr)
    End Sub
```
My suggestion here is to make this more formal, and have the compiler provide this as an overload of the built-in Len function.

**Comment by WaynePhillipsEA** [comment]
TypeName and VarType are also candidates for similar treatment, which would be particularly useful in generics.

**Comment by bclothier** [comment]
FWIW, in VB.NET there's [`NameOf` operator](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/nameof) and [`TypeOf` operator](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/typeof-operator). But both exist because type is considered as just another object rather than specially. Treating a type as an object makes it much easier to reason about the type, IMO, because you can write powerful reflection logic when it's just a plain object.

**Comment by wqweto** [comment]
@bclothier No, these two exactly are **not** examples of where type is treated as an object :-))

`NameOf` is clearly a special intrinsic as it's a shortcut to AST (inspect this node's `Name` property of similar) and nothing to do with object-orientedness of the type system in VB.Net (or C#)

`TypeOf` is an operator inherited from legacy COM world where it directly maps to a `IUnknown::QueryInterface` call. That's why it failes if the variable is `Nothing` (cannot call QI on NULL pointer). It could be implemented with type as objects with something like "take the type-object as this variable in A and take the singletop type-object of this type in B and finally compare if A and B are the same object". Could be but a more efficient way is possible for the compiler to emit too.

**Comment by bclothier** [comment]
RE: TypeOf -- show you how often I code in VB.NET. I assumed it was same as [C#'s `typeof` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#typeof-operator). 

Still, my point stands. You _can_ treat types as if they were objects. If you couldn't, then that code wouldn't be possible:

```
var myType = typeof(int);
Console.WriteLine(myType.Name);
```

The type-as-an-object is what make the reflection capability of .NET so powerful, IMO.

**Comment by WaynePhillipsEA** [comment]
No, there's a difference.  Reflection provides objects that **describe** the datatype.  A datatype symbol is itself not an object.  

Certainly, in tB, there is absolutely no precedent for passing a datatype symbol like an argument, except for the case of generics.  If we were to accept datatypes to be passed like arguments to intrinsic functions, this would require significant changes to the tB resolver, along with special casing for the handling of those intrinsics.  That's not happening under my watch, especially as there is a viable solution here using the generics syntax that tB already supports.

**Comment by wqweto** [comment]
I was wondering if it's possible to make [ITypeInfo](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-itypeinfo) on public/private interface more accessible?

Probably first implementation could use the wrapper in TLI and return it As Object i.e. supporting this syntatic sugar `Set oInfo = TypeOf(oMyObject)`.

Not sure it's worth it though the sintatic sugar as one can retrieve the same using `InterfaceInfoFromObject` global method from TLBINF32.DLL directly.

**Comment by WaynePhillipsEA** [comment]
Apologies, the point I'm trying to make is that passing types in that way is not something that the tB resolver currently supports (outside of generics), and so introducing that would be making this much more complicated than it needs to be.

So yes, Len(Of X), Name(Of X) etc are all preferable over making changes to the resolver.

**Comment by Kr00l** [comment]
What is Name(Of X) ?
Or do you meant TypeName(Of X) ?

**Comment by WaynePhillipsEA** [comment]
> I was wondering if it's possible to make [ITypeInfo](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-itypeinfo) on public/private interfaces more accessible?
> 
> Probably first implementation could use the wrapper in TLI and return it As Object i.e. supporting this syntatic sugar `Set oInfo = TypeOf(oMyObject)`.
> 
> Not sure it's worth the sintatic sugar though as one can retrieve the same using `InterfaceInfoFromObject` global method from TLBINF32.DLL directly.

I think we could potentially expand reflection support #585 to include general COM/ITypeInfo wrapping, thus avoiding the need for TLI library.  Isn't TLI 32-bit only if I remember correctly? (could be wrong)

**Comment by bclothier** [comment]
> So yes, Len(Of X), Name(Of X) etc are all preferable over making changes to the resolver

I now follow. Sorry - it must be my slow day. :) 

> What is Name(Of X) ?
Or do you meant TypeName(Of X) ?

Yes, although I never really use it. For example, this is possible with older DAO versions:

```
Dim r1 As DAO.Recordset
Dim r2 As ADODB.Recordset

Debug.Print TypeOf r1 Is DAO.Recordset 'True
Debug.Print TypeOf r1 Is ADODB.Recordset 'False
Debug.Print TypeOf r2 Is DAO.Recordset 'False
Debug.Print TypeOf r2 Is ADODB.Recordset 'True

Debug.Print TypeName(r1) = TypeName(r2) 'Really? 
```

(the current DAO model now has `Recordset2` which no longer equals but it's still inadequate because it doesn't provide library information so there are other ways `TypeName` can mislead. `VarType` or `TypeOf` are usually more useful.)

**Comment by mansellan** [comment]
FWIW, in .Net its almost always preferable to pass types as type parameters generically, rather than as `Type`. The latter predates generics in .Net. So avoiding `Type` in tB is a good call IMO.

**Comment by Kr00l** [comment]
Since Variants are disallowed for generics now a `Len(Of Variant)` will not be allowed anymore.
But it wouldn't make sense anyhow since Len() returns different for Variants.
MSDN.
_If varname is a Variant, Len treats it the same as a String and always returns the number of characters it contains_

But what would then `Len(Of String)` return? The same as LongPtr maybe?

**Comment by WaynePhillipsEA** [comment]
`LenB(Of datatype)` and `Len(Of datatype)` are now supported as of BETA 351.  Thanks all.
