### ISSUE TITLE
Quick-fix for missing implementations

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#604]
In v0.13.58, we now have an experimental quick-fix code action for adding missing Implements members:
![tbQuickFixImplements](https://user-images.githubusercontent.com/25738109/147454530-95c52051-e171-439e-9253-65af331cb75a.gif)

This is a work-in-progress, and currently only available for Implements statements (not WithEvents).  Please report any bugs or feedback relating to this experimental feature here.

Note that the keyboard shortcut is Ctrl+. once you've put the caret on the Implements statement.

**Comment by Greedquest** [comment]
Maybe add a default not implemented error in there somewhere (I like `Debug.Assert False, "Procedure not implemented yet"` because then if I hit this code I can edit it then and there as the editor highlights it for me. `Err.Raise 35` for _”Sub, Function, or Property not defined"_ could work too, I thought there was an interface member not implemented error number bit I can't find it on Google)

**Comment by bclothier** [comment]
Two feedbacks:

1) If the interface is large, the resulting list is large and it requires scrolling through all the options before we get to the last menu item to implement all. I think it should have a listbox within the menu so that you can keep a maximum size to the menu while exposing other menu items that don't correspond to a specific interface members.

2) It doesn't disambiguate; to avoid problems, we need to fully qualify the member to avoid ambiguous references:
```
Public Class Foo
  Implements OtherFoo.Foo
  
  Public Property Bar() As String Implements Foo.Bar 'which Foo? My Foo or OtherFoo's? 
  End Property
End Class
```

**Comment by WaynePhillipsEA** [comment]
> Maybe add a default not implemented error in there somewhere (I like `Debug.Assert False, "Procedure not implemented yet"` because then if I hit this code I can edit it then and there as the editor highlights it for me. `Err.Raise 35` for _"Sub, Function, or Property not defined"_ could work too, I thought there was an _'interface member not implemented'_ error number but I can't find it on Google)

Yes, that's a good idea.  From a COM perspective, callers would expect E_NOTIMPL (&H80004001).

**Comment by WaynePhillipsEA** [comment]
> Two feedbacks:
> 
> 1. If the interface is large, the resulting list is large and it requires scrolling through all the options before we get to the last menu item to implement all. I think it should have a listbox within the menu so that you can keep a maximum size to the menu while exposing other menu items that don't correspond to a specific interface members.
> 2. It doesn't disambiguate; to avoid problems, we need to fully qualify the member to avoid ambiguous references:
> 
> ```
> Public Class Foo
>   Implements OtherFoo.Foo
>   
>   Public Property Bar() As String Implements Foo.Bar 'which Foo? My Foo or OtherFoo's? 
>   End Property
> End Class
> ```

Thanks.   1) we don't have much control over the way the list is displayed, unfortunately.   We should be able to put the ALL option at the top of the list though.

2) Yes, I'll look at that.

**Comment by WaynePhillipsEA** [comment]
v0.13.59 fixes the ambiguity issue, adds a default Debug.Assert line and puts the 'add all' option at the top of the list.

**Comment by WaynePhillipsEA** [comment]
For a long time now you can use the combo-boxes to add missing members and events, just like in VBx.  Therefore, time to close this one.  Thanks.
