### ISSUE TITLE
Other IDEs

### ISSUE THREAD

**Issue by mansellan** [twinbasic/twinbasic#82]
**Is your feature request related to a problem?**
twinBASIC is implemented as an LSP/DAP server - is it possible to connect to it from IDEs other than VSCode?

**Describe the solution you'd like**
I'm thinking initially of Visual Studio and Rider, but there are tons of others.

**Additional context**
I appreciate that twinBASIC, the product, has to have a "primary" IDE, and I don't want to distract from that. But if someone wanted to independently try to connect other IDEs to the twinBASIC server process, and flag any protocol issues found, would that be acceptable? I appreciate that add-in hosted features like the future forms designer would necessarily be out-of-scope.

**Comment by retailcoder** [comment]
...the VBE, via Rubberduck 4.0?

**Comment by mansellan** [comment]
Yes, potentially. Probably easier with Avalon, as we'd own the entire message loop.

**Comment by WaynePhillipsEA** [comment]
Technically, yes.   The LSP and DAP protocols are implemented over sockets the communicate with the tB compiler.   There's also a dedicated host controller socket which handles project loading / saving etc, and there's also a virtual file system socket.   Quite a lot of work to port to another environment, but ultimately it is possible.

**Comment by retailcoder** [comment]
TBH I'm not seeing this happen with Rubberduck (maybe perhaps with a very-future "lite" version that would pretty much be a rewrite), but merely twinBASIC *offering* that possibility makes it more resilient than VB ever was, because the language gets to live beyond any particular IDE - the possibility of writing twinBASIC/VBA in the VBE, coupled with VBE tooling to support it, could effectively make the VBA subset of twinBASIC - and all the goodness that comes with it - accessible to *Joe in Accounting* with a locked-down workstation and no rights to install VSC!

**Comment by bclothier** [comment]
I think this issue can be closed partially because we already successfully switched to another IDE, and partially because this isn't very actionable. Best that an issue is opened to target a specific IDE. Wayne is on record as not going to support VS Code extension until next year, so that is likely true for any other IDEs as well.
