### ISSUE TITLE
vbp getting stuck with relative paths

### ISSUE THREAD

**Issue by mika76** [twinbasic/twinbasic#944]
(First posted in #703 but it was already closed so I thought I'd open a new bug)

@WaynePhillipsEA are relative paths working now? - I'm hitting issues opening a .vbp project (on release 60 https://github.com/WaynePhillipsEA/twinbasic/releases/tag/beta-60) - in m vbp there are a lot of relative paths which go up to the parent and then into other folders.

eg

Class=clsEvents; ..\COMMON\clsEvents.cls
Form=frmSealNumber.frm
Class=clsUpdator; ..\COMMON\clsUpdator.cls
Class=clsMD5Hash; ..\COMMON\clsMD5Hash.cls
Class=clsSystemInfo; ..\COMMON\clsSystemInfo.cls
Module=modRRTools; ..\RemoteLogin\modRRTools.bas
Twinbasic is just stuck on the "Please wait" loading screen. Also are there any log files anywhere I can look at to see what the problem might be?

**Comment by WaynePhillipsEA** [comment]
There doesn't seem to be a problem with relative paths.  It's more likely that something in your project is causing the compiler to crash.   Would you be able to share the project so that I can take a look?  (privately if necessary).   

ps Currently, the only log file available to you will appear after the VB6 project has been opened successfully.

**Comment by mika76** [comment]
@WaynePhillipsEA I don't think I will be allowed - the whole projects is a mess of interconnected source files being shared by multiple projects and many, many dependancies.

Any way you could put in some logging which we could report here in the future instead?

**Comment by mika76** [comment]
I will close this issue - I just tried to import with the latest release  (beta 131) and it imported.
